### ISSUE TITLE
Make sure it's clear about which properties MUST be queryable

### ISSUE THREAD

**Issue by giovannipizzi** [Materials-Consortia/OPTiMaDe#109]
Now, a `property` is `anything that can be in the filtering of results`.
Instead it should be what is returned by the API, and instead we should clearly mark which properties MUST be queryable by *any* implementation (the rest does not have to be).

**Comment by CasperWA** [comment]
We have a bit of a conflict now when defining `field` and `property`.
Since `field` is any "key" in the output, anywhere, shouldn't `property` be defined as a subset of `field`? In the sense that it can be any `field` under the top-level `data` field`?

**Comment by CasperWA** [comment]
As an addendum, this also makes `attributes` in and of itself a property. Is this what is intended?

**Comment by CasperWA** [comment]
According to the discussion in issue #12, it now seems that JSON has defined a `field` as the key of a JSON object (a Python dict) and a property is when you have both key and value together.

If we confine properties to only be a valid interpretation for `field`s (and their values) in the top-level `data` `field`, then it will be easy to reference "property fields" to be the only queryable options.

**Comment by ltalirz** [comment]
I would vote for adopting the rather general way the term "property" is used in JSON:

> Objects are the mapping type in JSON. They map “keys” to “values”. In JSON, the “keys” must always be strings. Each of these pairs is conventionally referred to as a “property”.

And add the "queryable" wherever applicable.

**Comment by coreyoses** [comment]
Should there also be a qualifier for "filterable", as a JSON value need not be filterable (e.g., a structure vs. cell volume)?

**Comment by giovannipizzi** [comment]
I think the meaning we intend for "queryable" is exactly what you mean with "filterable" - and indeed since we call it `filter` it might be a good idea to rename the field to "Filterable" and the sections "Filtering"

**Comment by rartino** [comment]
What is the status here: does @giovannipizzi or @CasperWA plan to create a second PR to match #126 to address this issue? Personally I consider this issue blocking for v0.10. We shouldn't make a release were we knowingly are vague about what properties can and cannot be used in filters.

**Comment by giovannipizzi** [comment]
I agree that this should be done as soon as possible. However, sadly I won't have time in the next 1-2 weeks, to draft this...

**Comment by rartino** [comment]
Good to know; unless I see anyone else take this one I will try to make an attempt at it.

**Comment by CasperWA** [comment]
I also do not have the time, unfortunately - at least for this week. However, I can dedicate time in next week to write it up - or just review your PR in detail, @rartino :)

**Comment by rartino** [comment]
I remove the blocking-release flag from here, since there now is a PR #150, where I instead put this flag.
