### ISSUE TITLE
Migrate away from using values in dictionary keys

### ISSUE THREAD

**Issue by merkys** [Materials-Consortia/OPTiMaDe#112]
An agreement was reached between @fawzi, @rartino and @sauliusg that values MUST NOT be used as dictionary keys. The main argument of such decision is the upcoming advent of queryable nested properties (e.g. dictionaries inside dictionaries; partially covered in #96). The following problems have been identified:
1. values in nested names might break identifier syntax of filtering language;
2. the user would need to query for the dictionary keys (suppose the user wants to query for all structures with sites with concentrations less than 0.001, but queries like `species.*.concentration < 0.001` are not going to be supported).

**Comment by merkys** [comment]
`species` seems to be the only attribute that has to be changed.

**Comment by merkys** [comment]
As #127 fixed the issue with `species`, I consider the current specification satisfying this requirement. However, the requirement of this issue should be built in the specification. Therefore, I keep this open.

**Comment by sauliusg** [comment]
The current filter syntax, AFAIU, does not permit Properties like `ident1.*.ident2`, or `ident1."value".ident2`. Do we need explicit explanation in the text in an informal way? If there is a risk of confusion, then yes, but adding informal text that duplicates a formal definition might end up in contradicting specs when the grammar changes in the future and we overlook the informal text?

Maybe, if we decide that the is a need to add an informal explanation about forbidden  `ident1.*.ident2` property constructs, we should add at the beginning of the spec that if a formal definition contradicts the informal text, the formal definition takes the precedence?

**Comment by merkys** [comment]
At present the issue is solved. I had made an attempt to put forward provisions to avoid it happening again in the future (#134), but after a live discussion with @sauliusg I've decided to retract the proposition due to both difficulties in formulating the requirement and unwillingness to introduce meta-specifications.
