### ISSUE TITLE
Querying on relationship, dot operator in grammar, change of sites definition

### ISSUE THREAD

**Issue by rartino** [Materials-Consortia/OPTiMaDe#116]
After some discussion in the provenance group, we want to do a PR with the following:
- Enable querying on relationships using the identifier syntax `<endpoint name>.id` that should for the purpose of formulating filters be thought of as a list of ids of entries under that endpoint.
- Conceptually the `<endpoint>` object (without the dot) should be thought of as its own "data type": it is a relationship. API Implementations do not need to include that object in the response alongside other properties, but MUST include information to indicate these relationships in some way. For example, in jsonapi output they are included under the `relationships` key in the standard jsonapi way.
- This phrasing opens the possibility that in the future we could take the route to allow, e.g. `references.author.last_name = "John"`, but we do not put that in the specification at this time.
- The `<identifier>.<identifier>.<...>` syntax is generally adopted to make queries on subfields of hierarchical data. Furthermore, if any segment in such a construct is a list, there is an implicit map operation to create a list out of those subelements; and, in the final step the list is always regarded as flattened (this needs to be formulated more precisely in the spec.) (partially addressed by #123)
- **However**, this suggest OPTIMaDe should not standardize on hierarchical data which uses data values as keys, which there also are other reasons to avoid. (#112)
- Hence, we also suggest to redefine `sites` to instead of begin a dictionary with the site name as a key, it should be a list of objects, with `name` as one of the keys alongside `chemical_elements`, etc.

**Edit by** @merkys: fixing typos, referencing #112

**Comment by merkys** [comment]
Overlaps with #96

**Comment by rartino** [comment]
This issue has, to a large degree, been addressed by PR #123 and #112, and is affected by #119, but it still remains when they have been merged to write up as a PR that relationships can be queried using `<type>.id` and explain why that works (`<type>` access a "relationship" and `<type>.id` means a list of ids of related `<type>` entries.) + the implicit map meaning of `list.id`.
