### ISSUE TITLE
Allow comments in JSON code snippets

### ISSUE THREAD

**Issue by giovannipizzi** [Materials-Consortia/OPTiMaDe#118]
## Description of the problem
Comments are not allowed in JSON and are highlighted in red by the GitHub parser:
```json
{
  "a": true
  // this is a simple JSON
}
```
However GitHub [provides also a `jsonc` language](https://github.com/github/linguist/blob/3a1bd3c3d3e741a8aaec4704f782e06f5cd2a00d/lib/linguist/languages.yml#L2294) meaning "JSON with comments" that accepts comments:
```jsonc
{
  "a": true
  // this is a simple JSON
}
```

## Task
Replace all
```
 ```json
```
with
```
 ```jsonc
```

**Comment by CasperWA** [comment]
Great! Was looking for this for a while - thanks!

**Comment by giovannipizzi** [comment]
I'm just waiting to do this because there is at least one PR (well, mine ;-) #50) that adds a new json snippet (without a `c` for consistency) so better to do this after a few PRs are merged (might be soon, anyway)

**Comment by CasperWA** [comment]
In addition, JSON apparently does not support incompletely written floats, e.g., `1.`.
This should be an easy fix alongside this addition. I found at least [one example](https://github.com/Materials-Consortia/OPTiMaDe/blob/develop/optimade.md#6210-assemblies) where this is used (see further down in the linked section).

**Comment by giovannipizzi** [comment]
Yes, with @rartino we also spotted this. Will do.

**Comment by giovannipizzi** [comment]
I'm going to work on this now
