### ISSUE TITLE
type and endpoint should have the same name

### ISSUE THREAD

**Issue by fawzi** [Materials-Consortia/OPTiMaDe#119]
Please remember to label your issues according to topic, type and [potentially more](https://github.com/Materials-Consortia/OPTiMaDe/wiki/Description-of-issue-labels).

**Comment by merkys** [comment]
I agree. Let's make it singular, i.e. `structure`, not `structures`. Pinging @rartino and @sauliusg as we have just discussed this.

**Comment by fawzi** [comment]
Currently:
```
/structures/some_id
```
reaches a structure
```json
{
  "type”: “structure”
  “id”: “some_id”
}
```

this is ugly and makes problems when defining relationships with different names

**Comment by rartino** [comment]
What?, do I understand right that you want to change the endpoints to be singular? Note that all examples in jsonapi uses plural(!)

@fawzi Can you explain a bit more about what the problem is that the endpoint name != the type name?

**Comment by merkys** [comment]
This issue actually might be a shortcoming of the JSON API spec. Suppose we have `relationships` in the response JSON API, but we don't have the related entries in top-level `included` (for example, the implementation does not support them). Then having only [Resource Identifier Objects](https://jsonapi.org/format/#document-resource-identifier-objects) there is no standard way to retrieve their contents (no standard `links`).

**Comment by dwinston** [comment]
Why then not make `type` plural? Then, given, `{type,id}`, you expect to be able to request `<base_url>/<type>/<id>`, e.g. `https://example.org/optimade/v1.0/structures/18`.

**Comment by rartino** [comment]
After some discussion with @fawzi and some thought, I'm coming to the same conclusion as @dwinston: using plural in the type field seems to be the least bad solution. While it makes my skin crawl a bit, it is something that few users are going to care about. Changing the endpoints to singular looks unusual and would be much more visible.

I do see the increased elegance in that URLs are derivable from (id, type). But yet I'm not fully convinced this is absolutely needed. Any implementation anyway has to encode a lot of optimade-specific info internally, e.g., the type of all filterable properties. It isn't precisely hard to encode a mapping between types and endpoint names for ~ 4 types.
