### ISSUE TITLE
Date data type

### ISSUE THREAD

**Issue by merkys** [Materials-Consortia/OPTiMaDe#139]
The current description of comparison operators does not cover the handling of the following cases:
1. <s>String vs. numeric types. My proposition: if one of the operands is numeric, then the string has to be converted to number, and a numeric comparison should be carried out. If the string does not convert to a number, emit error.</s>
2. Dates. Currently, the value of `time_stamp` is a date (expressed as `string` in JSON), thus I believe the API would benefit from being able to compare dates. My proposition: when filtered on date fields, the backend has to convert the query operand (in [ISO 8601](https://www.iso.org/standard/40874.html) with time zone) to internal date representation and compare to see which of the dates is earlier and which is later.
3. <s>Booleans. My proposition: if one of the operands is boolean, then the other has to be converted to boolean (`0`, `"0"`, `""` are `False`, rest being `True`), and `True` is greater than `False`.</s>

What do you think?

**Edit**: first case is already covered in "Type handling and conversions in comparisons", and the third case is not important for the specification right now; retitling the issue to match the second case.

**Comment by merkys** [comment]
Pinging @sauliusg as he originally spotted this deficiency. @sauliusg feel free to make addenda/corrigenda.

**Comment by rartino** [comment]
1) Isn't this covered in the subsection "Type handling and conversions in comparisons" in section 5.2? It says there that the comparison semantics follows the type of the property, and it is RECOMMENDED that an implementation try to convert into this type.

2) Right, the iso8601 dates we have right now (e.g., `last_modified`) claim to be strings. Probably makes sense to explicitly write up a date type with date comparison semantics. 

3) We don't have any boolean properties (yet). I'd be OK with a PR that consistently add booleans everywhere (including the section about type conversions.)

**Comment by merkys** [comment]
Indeed, most of the cases of type conversion are already covered in "Type handling and conversions in comparisons", I've overlooked that. Booleans could be left out for now.

> 2. Right, the iso8601 dates we have right now (e.g., `last_modified`) claim to be strings. Probably makes sense to explicitly write up a date type with date comparison semantics.

I'll open a PR for this.
