### ISSUE TITLE
Confusion of terms, restructuring/organization

### ISSUE THREAD

**Issue by rartino** [Materials-Consortia/OPTiMaDe#141]
As I'm working through a bunch of PRs I see some divergence and confusion in terms, as well as some disorganization.

- As discussed in #138 The definition of 'property' is now formally a generic name for key-value entries in dictionaries, whereas other text seems written with the intent of property referring to database-related-data returned in the output or that is filterable. 

 - The formal definition of 'Entry' (actually going back to the very first version) actually seems to be in error. Throughout the document we use 'Entry' to refer to specific "rows" of data. E.g., the section titles "Entry Listing Endpoints" and "Single Entry Endpoints". The definition says Entry is a *type* of resource. The confusion over this seems to have triggered the addition of a second term for the same thing borrowed from jsonapi: "Resource object". The intermixed use of these two terms now is somewhat confusing.

- There seems to an unclear overlap between '2. Term definitions' and '5.1' Lexical tokens'. I think we may want to merge 5.1 into 2.

- Throughout the document it seems we are losing the separation in terminology between an OPTiMaDe response and the jsonapi response format. We had (and I still hope have) the idea of allowing other output formats, e.g., HDF5, and for this it isn't ideal to (re)phrase things in ways that may make sense only in the context of json-formatted output. E.g., we have to be very careful with how we describe things like use of the 'relationship' feature of jsonapi.

**Comment by rartino** [comment]
I'll keep adding things that in my opinion would benefit from restructuring to this issue:
- Section 3.3.4. Unset optional properties is not about responses, but more about a general feature of OPTiMaDe and filtering. This should NOT be a subsection to 3.3 Responses, but rather directly under section 3. And we should look over the overlap with section 5 and possibly reduce it.

**Comment by merkys** [comment]
> * As discussed in #138 The definition of 'property' is now formally a generic name for key-value entries in dictionaries, whereas other text seems written with the intent of property referring to database-related-data returned in the output or that is filterable.

Indeed. I'd very much like to see it brought back, as there is a difference between property as in "any key in any dictionary" and "any key in `attributes` dictionary of any entry".

I agree with every other point in @rartino's posts here.

**Comment by rartino** [comment]
As commented in #138: I suppose we could call our database-related-data properties "entry properties" for clarity. That can be abbreviated as "properties" in segments of text where it is obvious that it is what is being referred to.

But in that case, I would change our main term definition to define entry property rather than property. I'm OK with either a term definition or just a comment elsewhere that says that in the context of json objects a property is a field-value pair.

**Comment by rartino** [comment]
To move over the discussion here from #138, I copy the last message of @ltalirz before that PR was closed:
> Before continuing this discussion, I think it would be helpful if @rartino or @merkys could provide a crystal clear definition of what subset of field-value pairs you mean by "entry properties" (or whatever name we end up choosing).
> I.e., given any possible response of the OPTiMaDe API, how do I decide whether a given field-value pair is an "entry property"?

> I ask this because I get the impression that the two of you already mean different things. The whole issue that led to the explicit definition of "property" is that e.g. section 6.1 (entitled "Properties used by multiple entry types") lists field-value pairs like type, which is not an attribute, and field-value pairs like last_modified which is an attribute.

**Comment by merkys** [comment]
Answer to @ltalirz (the definitions to my opinion):

* **field-value pair** is any *name-value pair* in any JSON *object* (terms in italic are as per [JSON specification in RFC 8259](https://tools.ietf.org/html/rfc8259#section-4))
* **entry property** is any field-value pair in `attributes` object of any entry, i.e., *member* of *attributes object* (terms in italic are as per [JSON API specification](https://jsonapi.org/format/#document-resource-object-attributes))

> The whole issue that led to the explicit definition of "property" is that e.g. section 6.1 (entitled "Properties used by multiple entry types") lists field-value pairs like type, which is not an attribute, and field-value pairs like last_modified which is an attribute.

`id` and `type` should be removed, leaving only entry properties (*attributes*) in this section.

**Comment by ltalirz** [comment]
@merkys Thanks for providing the definition. 

> * **field-value pair** is any *name-value pair* in any JSON *object* (terms in italic are as per [JSON specification in RFC 8259](https://tools.ietf.org/html/rfc8259#section-4))

Since you found RFC 8259 and it exclusively uses *name-value pair* (actually also: *name-value mapping*), should we simply adopt this as well?
If we can avoid it, I think we should not use both *field*  and *name* in our specification.

> * **entry property** is any field-value pair in `attributes` object of any entry, i.e., *member* of *attributes object* (terms in italic are as per [JSON API specification](https://jsonapi.org/format/#document-resource-object-attributes))

Let me try to split this up into a format-agnostic definition and a format-specific one:

* **entry property** Any field-value pair representing a property of a database entry. In the `json` response format, entry properties are represented as *members* of the *attributes* object (terms in italic are as per [JSON API specification](https://jsonapi.org/format/#document-resource-object-attributes)).

So, I understand this to mean that:
 * Only things returned in the `data` top-level field can be entry properties (not stuff in `meta`, `included`, `links`, `errors`, ...)
 * `type` and `id` are **not** entry properties since they are not attributes

@rartino Is this the definition you had in mind?

**Comment by merkys** [comment]
> Since you found RFC 8259 and it exclusively uses name-value pair (actually also: name-value mapping), should we simply adopt this as well?

In principle yes, but as @rartino wrote in https://github.com/Materials-Consortia/OPTiMaDe/pull/145#pullrequestreview-255661534 it would be better to switch to format-agnostic terms. Just used JSON API terms here for clarity.

> * Only things returned in the data top-level field can be entry properties (not stuff in meta, included, links, errors, ...)
> * type and id are not entry properties since they are not attributes

Precisely.

**Comment by rartino** [comment]
@ltalirz, @merkys 

Your split into the format-agnostic and format-specific parts is very important. The actual term definition is the format-agnostic one. And as we discuss this, I'm finding that my position is that the format-specific definition should be moved down to Sec 3, because it isn't part of a term definition, it is an instruction about how to represent something in a specific response format.

`id` and `type` probably should be regarded as properties. Because, we want them returned also by all other response formats (right?).

**Comment by rartino** [comment]
So, I'm looking over this right now, as the present situation interferes with resolving #109.

Here is what I am at for the output-agnostic term definitions:

----

* **Database provider**: A service that provides one or more databases with data desired to be made available using the OPTiMaDe API. 
* **Database-provider-specific prefix**: Every database provider is designated a unique prefix. 
    The prefix is used to separate the namespaces used by provider-specific extensions. 
    These are defined in [Appendix 1](#h.app1).
* **API implementation**: A realization of the OPTiMaDe API that a database provider uses to serve data out of a database.
* **Entry**: A single instance of a specific type of resource served by the API implementation. 
    For example, a structures entry is comprised by data that pertain to a single structure. 
* **Entry type**: Entries are categorized into types, e.g., structures, calculations, references.
* **Entry property**: One data item that pertains to an entry, e.g., the chemical formula of a structure. 
    All entry properties are given a name which starts with a lowercase letter ([a-z]) or an underscore ("_") and is followed by any number of lowercase alphanumerics ([a-z0-9]) and underscores ("_"). 
	Entry property names MUST NOT be the name of any Entry type.
* **Entry property value types**:
  * Basic types: **string**, **integer**, **float**, **boolean**, **timestamp**.
  * **list**: an ordered collection of items of one and the same basic type.
  * **dictionary**: an associative array of **keys** and **values**, where **keys** are pre-determined strings, i.e., for the same entry property, the **keys** remains the same between different entries whereas the **values** change.
* **Queryable property**: An entry property that can be used in the filtering of results. 
  For more information see section [3.5. Queryable Properties](#h.3.5).
* **ID**: The ID entry property is a unique identifier referencing a specific entry in the database.
  Taken together, the ID and entry type MUST uniquely identify the entry.
  IDs MUST be URL-safe strings; in particular, they MUST NOT contain commas.
  Reasonably short IDs are encouraged and SHOULD NOT be longer than 255 characters.
  IDs do not need to be immutable, and MUST NOT be a reserved word.
* **Immutable ID**: A unique identifier that specifies a specific resource in a
  database that MUST be immutable.
* **Reserved words**: The list of reserved words in this standard is:
  `info`.

----

**Comment by merkys** [comment]
> `id` and `type` probably should be regarded as properties. Because, we want them returned also by all other response formats (right?).

I am leaning towards supporting this. Maybe it's just the JSON API that draws a line between `id` and `type` and the rest of the properties. Other formats might do differently.

**Comment by merkys** [comment]
@rartino didn't #150 fix this issue?

**Comment by rartino** [comment]
Not the extra point I posted as the second command. But, all the discussion here pertains to the top post, so I'll close this and re-open an issue about that.
