### ISSUE TITLE
Are we ready to release v0.10?

### ISSUE THREAD

**Issue by rartino** [Materials-Consortia/OPTiMaDe#151]
At the end of the meeting, we said to give two weeks to get final things in **if the activity died down**.

The activity has no so much died down, and I think we have a few quite important PRs to get in. I have taken the liberty to mark a few with the "release-blocking" label. 

I vote that we hold the release until either the activity dies down, or these PRs are accepted. If we haven't released by ~June~ July 5 (which I really hope we will), we can re-assess the situation again.

Any thoughts?

**Edit**: If there are any other issues (or PRs) that seem release-blocking, please bring them to attention here.

**Comment by gmrigna** [comment]
I would suggest indeed to allow for one more week (July 5, not June @rartino).

**Comment by rartino** [comment]
I added the blocking-release flag to #65. Version number negotiation is something we probably want to get right in an as early release as possible.

**Comment by rartino** [comment]
It is June 5, so I am re-evaluating the situation.

The rate of progress has clearly died down now. 

**Remaining blockers:**
* #154 is finished, has one approval, and is sitting idle for another approval. Please?
* #144: we are very close to finishing this.

We really should wait to get these through before releasing.

**Open issues with potentially major impact on implementations:**
* #150 wants to remake the rules for returning unknown/`null` values in the output. This may be met with protests if people spend time implementing the presently mandated handling...
* #70 has, in my opinion, a fantastic idea of moving `/structures/info` -> `/info/structures` and remove all limitations on IDs. We could even skip having the `local_id` property, since databases can then always use their own ids as the main ID, for which I see many benefits. However, if we release v0.10 and implementations start to appear, this is not a very nice change to push on people.

These are the only really problematic ones I find. I can do the PRs, but they need feedback and approvals. If there are two people still around and willing to help get these through over the weekend/next week, make yourselves known. Otherwise I guess we have to push v0.10 as it is.

**Comment by merkys** [comment]
I guess v0.10 is fine even without #154 and #144, which can be fixed in v0.10.1 (as bugs). It would be nice to have a release for all the things discussed and included in the specification during this year's workshop, so people could start working implementing *stable* standard. For sure more issues will be discovered on the way.

**Comment by rartino** [comment]
I'd understand about #152, #70. 

But,  
#144 fixes a serious bug in the specification. We really shouldn't release new versions with known major bugs.
#154 changes how version negotiation works, which really isn't something one should mess with between more versions than necessary.

And, also, both of them are done. All we need is for one more person to sign off on them.

There is a meeting planned on Friday; if no one else is present here, we'll have to take the decision there.

**Comment by merkys** [comment]
Right, both #144 and #154 are one approval short of merging. Release can wait for that.

**Comment by merkys** [comment]
I have taken liberty to mark #111 as release-critical.

**Comment by rartino** [comment]
v0.10.0 is released! Closing this.
