### ISSUE TITLE
UnicodeHighChar comment

### ISSUE THREAD

**Issue by rartino** [Materials-Consortia/OPTiMaDe#153]
I see that this comment has remained in the EBNF grammar:
```
(* The 'UnicodeHighChar' specifies all Unicode characters above 0x7F;
   the syntax used is the one compatible with Grammatica: *)

UnicodeHighChar = ? [^\x00-\x7F] ? ;
```

But, if I remember what @sauliusg  told me: we *thought* this syntax was compatible with Grammatica, but it is not due to what appears to be a bug in Java's regex implementation (present at least in the version of Java that @sauliusg was running...). This regex syntax is however very broadly supported across programming languages with regex support.

Hence, I suggest that we change that comment into something like:
```
(* A 'UnicodeHighChar' is any Unicode character above 0x7F. 
It is specified in this grammar by an extension to EBNF that allows a regular expression. *)
```

**Comment by sauliusg** [comment]
Thath's right, the rest-over comments should be removed. Thanks, @rartino , for spotting it! The text is fine. Maybe we need to clarify further:
`It is specified in this grammar by an extension to EBNF that allows a regular expression to specify terminal symbol ranges.`
