### ISSUE TITLE
Changes in 'Allowing for unknown/null coordinates' (eec3b0d) lost !

### ISSUE THREAD

**Issue by rartino** [Materials-Consortia/OPTiMaDe#163]
As I was responding to the conversation in #159, I discovered that we somehow have lost the changes introduced by @giovannipizzi about how `null` is allowed in `cartesian_site_positions` in eec3b0d !

**Edit:** I see that three commits show these lines as removed, 254e446, 1deb6e68dcdb4accc727dc7a5c2cb96ece775c0b, c0a72939644bf354608f55e5fac0d855c7d0442c (one of them a commit by me). It is *possible* I mis-merged this in a rebase in the chemical formula PR since that affected the same region of the text. I will go through those changes again and check that nothing else was lost.

**Comment by rartino** [comment]
Indeed, I dug up the relevant PR, #127 

The github diff do not show these lines removed as part of the merge:
  https://github.com/Materials-Consortia/OPTiMaDe/pull/127/files
which IMHO seems broken. It seems the diff should display all changes relative to the branch it is going to be merged into.

**Comment by rartino** [comment]
Well, I now also see these lines removed in 1deb6e68dcdb4accc727dc7a5c2cb96ece775c0b, c0a72939644bf354608f55e5fac0d855c7d0442c (one of them a commit by me...). So, it is clear I do not know enough about git history digging to understand what actually happened. Maybe someone who is better at this can help clarify the issue.

**Comment by giovannipizzi** [comment]
Maybe in #123 there was quite some work to modify and simplify the description of how to deal with null values and this was removed consciously? Anyway, I suggest reintroducing the sentence

**Comment by CasperWA** [comment]
I will redo the changes introduced by @giovannipizzi, collecting it in a single commit and making @giovannipizzi the author of this commit.
It seems we're also missing `all_coordinates_known` that was introduced in this PR.

**Comment by rartino** [comment]
Wait, wasn't `all_coordinates_known` intentionally removed by d1b7c1e707685bb8992b0b98b235c337f2996c10? It is superseded by `structure_features`. I should not be put back.
