### ISSUE TITLE
Is the example of a string token correct?

### ISSUE THREAD

**Issue by rartino** [Materials-Consortia/OPTiMaDe#167]
The specification presently contains in Sec. 5.1.:

---

An example of the escaped string value is given below:
  
    * "A double quote character (""", ASCII symbol 92 dec) MUST be prepended by
      a backslash ("\\", ASCII symbol 92 dec) when it is a part of the value and
      not a delimiter; the backslash character "\\" itself MUST be preceded by
      another backslash, forming a double backslash: \\\\"

(Note that at the end of the string value above the four final backslashes
represent the two terminal backslashes in the value, and the final double
quote is a terminator, it is not escaped).

---

Is the example correct? Doesn't all double quote characters need to be individually escaped, and why is there three in a row in the first line? Should this rather be?:

    * "A double quote character (\", ASCII symbol 92 dec) MUST be prepended by
      a backslash (\\, ASCII symbol 92 dec) when it is a part of the value and
      not a delimiter; the backslash character \"\\\" itself MUST be preceded by
      another backslash, forming a double backslash: \\\\"

Pinging @sauliusg as I think this text originated from him (?)

**Comment by merkys** [comment]
I think this should be:

    "A double quote character (\"\"\", ASCII symbol 92 dec) MUST be prepended by
    a backslash (\"\\\", ASCII symbol 92 dec) when it is a part of the value and
    not a delimiter; the backslash character \"\\\" itself MUST be preceded by
    another backslash, forming a double backslash: \"\\\\\""

My assumption is that all character sequences in the example should be put in double quotes.

I suggest omitting the bullet point, as it is not a part of the example.

**Comment by rartino** [comment]
Pinging @sauliusg to take a look, since I think you wrote this example.

**Comment by sauliusg** [comment]
In my understanding the suggested changes are not correct; when I quoted the charter I meant the ASCII character itself, not the OPTiMaDe string containing that character.

This is a usual character-metacharacter problem. Since this causes confusion, maybe we omit the quoted characters at all and leave just character names. The previously quoted [SQL standard draft](http://www.contrib.andrew.cmu.edu/~shadow/sql/sql1992.txt) uses this approach, which is formally correct and understandable, even though a bit tough to read...

**Comment by sauliusg** [comment]
I usually try to write character references in the following way:

`Strings are delimited by double-quote characters ('"', ASCII symbol code 50 decimal, 32 hex).`

This notation implies that single-quotes in this sentence are meta-characters, they are quoting the double quote character (which is _mentioned_, but not _used_ in this context). To clarify the intent and to remove any ambiguities, the encoding and numeric code of the mentioned character (the double-quote) is provided.

The only problem is to mention the single-quote character; in the case I use double-quotes to mention them:

`A single-quote character ("'", ASCII symbol code 55 decimal, 37 hex) has no special meaning in OPTiMaDe Filter strings.`

Again, it is implied that in this context the double quote characters are _used_ (they are used to quote a double-quote character), and the single quote character is _mentioned_.

None of the use of quote characters above has anything to do with character strings, neither in OPTiMaDe Filters nor in any other languages. The last sentence, when represented in a Filter string, will have to escape the double-quote character mentioned in the sentence and would look like:

`sentence = "A single-quote character (\"'\", ASCII symbol code 55 decimal, 37 hex) has no special meaning in OPTiMaDe Filter strings."`

I am hoping that the quoting use patterns in the sentences above are familiar enough and would be recognisable from the context, without the formal definition of characters, meta-characters and escaping rules. We can give the formal rules, I believe, but they would be quite perplexing if made mathematically strict. One of the probelwms that will surface is that the description itself will need meta-meta-characters to quote the meta-characters that are described, and we will need to distinguish several layers of quoting (quoting meta-meta-characters in the meta-character description; quoting meta-characters in the string description; quoting meta-characters in the strings; quoting pattern special characters in patterns that are encoded in quoted strings). To my taste that gives more confusion than clarification, so unless we have an automated procedure (like EBNF parser) that processes such formal definitions, I see no point in presenting them for humans.

Does that make sense?

PS:

On a Linux command line (bash), quotes of the above filter sentence need further escaping; both variants provided below work:

```
saulius@koala sauliusg-optimade-specification/ $ tests/tools/grammatiker/BNF/scripts/grammatica-tree tests/generated/Filter.g <(echo "sentence = \"A single-quote character (\\\"'\\\", ASCII symbol code 55 decimal, 37 hex) has no special meaning in OPTiMaDe Filter strings.\"")
```

or 

```
saulius@koala sauliusg-optimade-specification/ $ tests/tools/grammatiker/BNF/scripts/grammatica-tree tests/generated/Filter.g <(echo 'sentence = "A single-quote character (\"'"'"'\", ASCII symbol code 55 decimal, 37 hex) has no special meaning in OPTiMaDe Filter strings."')
```

(both give the same parse tree :)

```
saulius@koala sauliusg-optimade-specification/ $ tests/tools/grammatiker/BNF/scripts/grammatica-tree tests/generated/Filter.g <(echo 'sentence = "A single-quote character (\"'"'"'\", ASCII symbol code 55 decimal, 37 hex) has no special meaning in OPTiMaDe Filter strings."') > 1.tree 
saulius@koala sauliusg-optimade-specification/ $ tests/tools/grammatiker/BNF/scripts/grammatica-tree tests/generated/Filter.g <(echo "sentence = \"A single-quote character (\\\"'\\\", ASCII symbol code 55 decimal, 37 hex) has no special meaning in OPTiMaDe Filter strings.\"") > 2.tree 
saulius@koala sauliusg-optimade-specification/ $ diff 1.tree 2.tree 
```

**Comment by sauliusg** [comment]
> Pinging @sauliusg as I think this text originated from him (?)

I do not remember writing it this way: as said, I would use slightly different conventions displayed above.

I think the latest edit was by @rartino :

```
git annotate optimade.md
3c51cc37        (Rickard Armiento       2019-05-20 16:58:10 +0200       1156)      * "A double quote character (""", ASCII symbol 92 dec) MUST be prepende
3c51cc37        (Rickard Armiento       2019-05-20 16:58:10 +0200       1157)        a backslash ("\\", ASCII symbol 92 dec) when it is a part of the valu
3c51cc37        (Rickard Armiento       2019-05-20 16:58:10 +0200       1158)        not a delimiter; the backslash character "\\" itself MUST be preceded
3c51cc37        (Rickard Armiento       2019-05-20 16:58:10 +0200       1159)        another backslash, forming a double backslash: \\\\"
```

I did not trace it back; maybe the original text was mine but this is not so important IMHO.

If you want I can change all character references in the text using the style which I showed above.

**Comment by rartino** [comment]
> > Pinging @sauliusg as I think this text originated from him (?)
> 
> I do not remember writing it this way: as said, I would use slightly different conventions displayed above.
> 
> I think the latest edit was by @rartino :

Sorry, I wasn't trying to pass blame as much as trying to get the person most knowledgeable about this segment of text to look at it. But for posterity, the sentence goes back verbatim to the very first commit coming from when we converted the Google doc into markdown, so lets say that it is unknowable from whom this originated :)

**Comment by sauliusg** [comment]
No need to be sorry, I think nobody blames anybody (remember, it was `git annotate`, not `git blame` :)

As said, if you, @rartino , and @merkys , and others think that my suggestion of character quoting is OK, and my examples of strings are intelligible, I can modify the 1.10.1-develop to follow these conventions, or someone else can do this and I can have a look. 

What makes me confident about these examples is that I can put them into our Filter parser and get the correct parse tree :)

**Comment by rartino** [comment]
@sauliusg, it seems we are discussing two things here:
- Which convention to use when quoting single characters. I don't have any strong feelings about this, as long as we avoid """ as a quoted double quote, '"' is fine with me. 
- To need to correct the example so that it correctly escapes the double quotes. Other than that it seems incorrectly escaped, I like the example text as it demonstrates that a double backslashes in output requires four backslashes in input.

However, the next thing I have planned is the conversion to RST, so I will hold writing this up as a PR until that PR is merged...
