### ISSUE TITLE
Contributors - alphabetical order

### ISSUE THREAD

**Issue by CasperWA** [Materials-Consortia/OPTiMaDe#179]
> Also, I see that for alphabetical order, my name "Ri" should be above "Ro". If there are further edits to the file, please fix that. (Otherwise I'll do a PR in a week or so.)
>      - _@rartino_

I believe the alphabetical order is for the last names.
However, for you is was indeed mixed up "Ar" before "Av".
This should be fixed in the API spec repository as well!

_Originally posted by @CasperWA in https://github.com/Materials-Consortia/materials-consortia.github.io/pull/3#issuecomment-513397546_

**Comment by rartino** [comment]
I'll write a PR if no one else does. We might also want to check all authors to check that everyone is in the right order.

**Comment by rartino** [comment]
This was closed by #194
