### ISSUE TITLE
XOR operator in filtering language

### ISSUE THREAD

**Issue by rartino** [Materials-Consortia/OPTiMaDe#18]
The suggestion is to adopt the XOR operator to the query language.

**Comment by giovannipizzi** [comment]
I'm not sure if the XOR operator is what we actually want. I think this  was discussed in the context of `my_set HAS ONLY ONE ELEMENT IN list`. However, translating this to 
`(my_set HAS ELEMENT list[0]) XOR (my_set HAS ELEMENT list[1])` works if `len(list) == 2`, but not for longer lists.

For instance  if `my_set = [a,b,c]` and `list = [a,b,c]`, then we have
```
(my_set HAS ELEMENT list[0]) XOR (my_set HAS ELEMENT list[1]) XOR (my_set HAS ELEMENT list[2])
(my_set HAS ELEMENT a) XOR (my_set HAS ELEMENT b) XOR (my_set HAS ELEMENT c)
True XOR True XOR True
False XOR True
True
```
While here we would like to get `False`.

(Reason: `XOR` of `n` elements, logically, is not "only one" but it gives a "parity bit" (returns `True` if we have an odd number of `True` elements, `False` if the number of `True` elements is even)

**Comment by rartino** [comment]
Yes, it indeed turns out it is quite difficult to rewrite a general "ONE OF" operator into other boolean logic operators. Most high level languages doesn't have a normal XOR, so we likely don't need it either.

The question of the reduction of a `HAS ONLY ONE` "set operator" is also less relevant now that this suggestion was separated out from the others in issue #16. (Also, as Fawzi also correctly pointed out, it isn't a set operator, but a query on cardinality). 

So, my recommendation is to reject XOR.

**Comment by giovannipizzi** [comment]
I agree. I close this issue then.
