### ISSUE TITLE
OPTIMADE logo FINAL

### ISSUE THREAD

**Issue by blokhin** [Materials-Consortia/OPTIMADE#185]
Dear all, here are a few shortlisted versions, which differ by the leg thickness and some other minor details. Please, feel free to vote and to re-distribute (CC BY 4.0), you may cut one out of a triple.

**Comment by blokhin** [comment]
![4](https://user-images.githubusercontent.com/177388/65804728-35239300-e183-11e9-8919-240d5739413c.png)

**Comment by blokhin** [comment]
![5](https://user-images.githubusercontent.com/177388/65804758-42d91880-e183-11e9-896e-5648daba1302.png)

**Comment by blokhin** [comment]
![6](https://user-images.githubusercontent.com/177388/65804779-53898e80-e183-11e9-9e15-2141b8a31892.png)

**Comment by blokhin** [comment]
![6_1](https://user-images.githubusercontent.com/177388/65804791-5f755080-e183-11e9-93fd-6045aecd25f3.png)

**Comment by blokhin** [comment]
![6_2](https://user-images.githubusercontent.com/177388/65804805-6b611280-e183-11e9-8938-d932080336ca.png)

**Comment by blokhin** [comment]
![7](https://user-images.githubusercontent.com/177388/65804812-7ae05b80-e183-11e9-9e13-00b54849c802.png)

**Comment by gjc29** [comment]
I like the logo, but I would suggest that the word OPTiMaDe is reverted to its previous mixed capitalization please?

**Comment by blokhin** [comment]
Hi Gareth,

please see the reasoning of Leopold and Giovanni, who gave [pretty strong arguments](https://github.com/Materials-Consortia/OPTiMaDe/issues/67#issuecomment-504695008) for the uniform capitalization, and Gian-Marco perfectly got that point.

**Comment by rartino** [comment]
@blokhin, can you please also post the original version of @giovannipizzi that got the most hearts last iteration to make sure we are making progress? Personally, I liked @giovannipizzi's use of boldface in the original logo text.

Should we vote on these, or how do we progress? 

Also, isn't changing the capitalization a separate issue from the logo? If we all agree on doing that change before 1.0, it needs to come with a PR that changes the capitalization throughout the specification text.

**Comment by blokhin** [comment]
@rartino that's the original Giovanni's version:

<img width="659" alt="59997812-37df8b00-965e-11e9-9453-cfbc0e919c16 1" src="https://user-images.githubusercontent.com/177388/68481937-bb2e0180-0238-11ea-9ef5-cfb4a8a75ed1.png">

**Comment by blokhin** [comment]
@gjc29 orig caps:
![v3_orig_caps](https://user-images.githubusercontent.com/177388/68484029-da2e9280-023c-11ea-8692-e9ee7440a64c.png)

**Comment by blokhin** [comment]
Orig caps with the outer hexagon
![v3_hex_thick_orig_caps](https://user-images.githubusercontent.com/177388/68484155-077b4080-023d-11ea-87c1-70fcf0c0b204.png)

**Comment by rartino** [comment]
@blokhin Assuming we are going to go with the sixth post (which at this time has three hearts) or the post just above this one, depending on how the voting shakes out on the capitalization; do you have svg files for those? Can you please distribute them? Thanks!

**Comment by blokhin** [comment]
Sure, I'll post one without the letters for now.
[optimade_logo.svg.txt](https://github.com/Materials-Consortia/OPTiMaDe/files/4149082/optimade_logo.svg.txt)

**Comment by ml-evs** [comment]
Any chance we could make the grey connections between the limbs a tad darker? It's basically the same as GitHub's grey so they don't show up at all in our [gh org banner](https://github.com/Materials-Consortia).

**Comment by mkhorton** [comment]
@ml-evs you can edit the svg directly too if you'd like to try some variations, just ctrl+f `#f5f5f5` and replace with the grey of your choice

**Comment by rartino** [comment]
@blokhin Thanks!

@ml-evs The grey is actually pretty noticeable in the gh org banner for me. Can you try to adjust the colors so it looks good on your monitor?, and then we can perhaps settle for that.

**Comment by ml-evs** [comment]
If it's just me then there's no need. Here's "what it looks like for me", if you can resolve these colours on your monitors then ignore me! I know I can edit the svg, I just didn't want to make an executive decision...

![image](https://user-images.githubusercontent.com/7916000/73698246-7cdd9c80-46d8-11ea-8221-0269c93b1e59.png)

**Comment by rartino** [comment]
This isn't really something you can show with a screenshot as it pertains to how your monitor is calibrated to show colors.

But if the bars show poorly on your monitor, I'm sure others would have the same issue. My thinking is that if you edit it until it looks good on your monitor, that likely generally improves the logo (since it is less of a problem if the bars are "too dark")

**Comment by ml-evs** [comment]
I understand, I just wanted to check everyone else was looking in the same place as me :) This seems to replicate across all my devices... I'll have a play with it.

**Comment by ml-evs** [comment]
Replacing #f5f5f5 with #e8e8e8 makes it much clearer at my end against the #fafbfc background (though there's still a definite chance it's just my eyes).

[optimade_logo.svg.txt](https://github.com/Materials-Consortia/OPTiMaDe/files/4150679/optimade_logo.svg.txt)

**Comment by merkys** [comment]
> I understand, I just wanted to check everyone else was looking in the same place as me :) This seems to replicate across all my devices... I'll have a play with it.

The links are poorly visible to me too. I have my screens at factory default, but not sure about the calibration status of my eyes.

**Comment by blokhin** [comment]
I updated the org logo. Is it better now?

**Comment by rartino** [comment]
@blokhin Thanks for the work with this. So, it seems we are landing in "OPTIMADE" with #e8e8e8 grey while otherwise equal to the now 4-times hearted logo posted Sept 28, 2019, right? 

So, for the website updates and elsewhere, it would be useful with svg and png versions for each of your "row" versions of that logo. Do you want to create those? (Otherwise, perhaps you can share your source file with the texts included to create those versions?) I think a good place to put them would be on our GitHub wiki.

**Comment by blokhin** [comment]
@rartino sorry, very busy last days, will respond in a while.

**Comment by blokhin** [comment]
Here we are:

[optimade-logo-final.zip](https://github.com/Materials-Consortia/OPTiMaDe/files/4307187/optimade-logo-final.zip)

Please, check.

SVGs are editable. License is CC-BY-4.0

**Comment by rartino** [comment]
Note: I uploaded these to our wiki, here: https://github.com/Materials-Consortia/OPTIMADE/wiki/Logotypes-and-graphics , so we don't have to dig through the closed issues to find them :-)
