### ISSUE TITLE
Capitalization of OPTiMaDe: voting in progress

### ISSUE THREAD

**Issue by rartino** [Materials-Consortia/OPTiMaDe#193]
As discussed in #67 and #185 there is a proposal to change the capitalization of how we write OPTiMaDe. 

These are the possibilities I see:
- OPTIMADE
- OPTiMaDe
- optimade
- OPTiMaDe in text, and OPTIMADE just in our logo.
- **Edit:** added: Optimade 

I feel uneasy changing the capitalization now right before v1.0 without a larger vote, which would only be possible at an in-person-meeting.

**Comment by merkys** [comment]
I too don't feel comfortable with changing the capitalization right now. I suppose we can change the capitalization at any time later (minor release), as such change will not affect the API.

**Comment by gmrigna** [comment]
I do not have strong feelings about this. But I agree with @merkys that this can be changed at any later time.

**Comment by blokhin** [comment]
Indeed, what if anyone uses any capitalization they prefer? The logo might exist in several options.

**Comment by mkhorton** [comment]
I would vote in favor of "Optimade," and treat it as any other proper noun. All capitalized or all lowercase also seem fine to me.

I would specifically vote against the inter-capped version "OPTiMaDe": this seems awkward and difficult to remember. This is only my own opinion, but seems shared by @ltalirz, @giovannipizzi  and others. Either way, I think the decision should be made final for the v1 spec and paper and not changed after that.

**Comment by rartino** [comment]
Let's try this. Please, everyone, show your preference by "reacting" with heart icons to the alternatives below.

**Comment by rartino** [comment]
OPTIMADE

**Comment by rartino** [comment]
OPTiMaDe

**Comment by rartino** [comment]
optimade

**Comment by rartino** [comment]
OPTiMaDe in text, and OPTIMADE just in our logo.

**Comment by rartino** [comment]
Optimade

**Comment by merkys** [comment]
> I too don't feel comfortable with changing the capitalization right now. I suppose we can change the capitalization at any time later (minor release), as such change will not affect the API.

On the second thought, minor release to us might be a serious change for implementers.

For example, I'm maintaining [Materials-Consortia/OPTiMaDe-Filter](https://github.com/Materials-Consortia/OPTiMaDe-Filter), filter language reader/writer in Perl language. The package enters Comprehensive Perl Archive Network (CPAN) as 'OPTiMaDe-Filter', thus I'll have to rename the package should the capitalization change. So I'd better decide this before v1.0 once and for all.

**Comment by giovannipizzi** [comment]
BTW - this thread looks like a dating app now! :-D
<img width="897" alt="Screenshot 2019-12-13 at 14 14 21" src="https://user-images.githubusercontent.com/16132028/70802848-e1543d80-1db2-11ea-98c1-20dee1ce062b.png">

**Comment by giovannipizzi** [comment]
A comment - I still think that in the code it's ok to use all lowercase.

**Comment by merkys** [comment]
@rartino will this be closed for v1.0~rc1, or should we give some more time until the v1.0 proper?

**Comment by rartino** [comment]
I suggest we bring this up on the next teleconference, and if agreement, close it at that point.

**Comment by ml-evs** [comment]
I believe we reached agreement on this, and can close? Please reopen if not.

**Comment by rartino** [comment]
Wouldn't it make sense to wait with closing this until we accept a PR that changes the capitalization?

**Comment by merkys** [comment]
Would anyone volunteer to prepare a PR? Should be easy.

**Comment by ml-evs** [comment]
> Wouldn't it make sense to wait with closing this until we accept a PR that changes the capitalization?

Yes, sorry, I'm just pushing that PR! Got a bit ahead of myself.
