### ISSUE TITLE
Format of 'lattice_vectors' is unclear for 2D, 1D and 0D systems

### ISSUE THREAD

**Issue by merkys** [Materials-Consortia/OPTiMaDe#196]
Specification defines `lattice_vectors` as three lattice vectors in Cartesian coordinates. However, it is not clear how the vectors are defined for nonperiodic dimensions. Currently it seems that such vectors are ignored, and as such can contain any values. But it would probably make sense to have a default, and I would suggest having `null`s for all the coordinates of vectors in nonperiodic dimensions.

An example of a 2D surface on XZ plane:
```
...
  "dimension_types": [1, 0, 1],
  "lattice_vectors": [[4, 0, 0], [null, null, null], [0, 0, 4]],
...
```

**Comment by rartino** [comment]
Do you think it is OK to merely suggest `null`s, but allow any number? (Preferably not even "SHOULD be null", but "MAY be null".)

I was a somewhat strong proponent for standardizing on reduced coordinates. Hence, I will certainly provide an `omdb_reduced_site_positions` alongside the standard `cartesian_site_positions`. In reduced coordinates, it makes sense to have lattice vectors also for the non-periodic coordinates, they act as multipliers for the coordinates in the `omdb_reduced_site_positions` list, so, for me, those values are going to be meaningful.

**Comment by merkys** [comment]
Non-`null` values indeed make sense having considered the reduced coordinates. Is there an issue open for their inclusion? Maybe we could get `reduced_site_positions` added before v1.0 release?

**Comment by rartino** [comment]
No issue as far as I know. I've only planned it as a database-specific property. Unless multiple databases chime in an say it is very useful for them, we can standardize it next meeting.

**Comment by merkys** [comment]
I'd suggest either to:

1. Standardize `reduced_site_positions` for v1.0 and require non-`null` values when `reduced_site_positions` is present;
2. Leave `reduced_site_positions` for v1.1 and discourage non-`null` values for nonperiodic vectors until then.

What do you think?

**Comment by rartino** [comment]
I say, 2, but not so much discourage non-`null` values as saying that values MAY be `null`.

**Comment by merkys** [comment]
> But if someone wants to do 1, I'll be happy to merge that PR.

I have opened PR #206.
