### ISSUE TITLE
Add a ChangeLog

### ISSUE THREAD

**Issue by merkys** [Materials-Consortia/OPTIMADE#197]
A ChangeLog would help both the spec developers and the implementers to track spec modifications between releases without the need to resort to reading git logs.

**Comment by ml-evs** [comment]
Are the summaries in the [released tags](https://github.com/Materials-Consortia/OPTIMADE/releases) sufficient, or should we make a changelog file containing them too?

**Comment by merkys** [comment]
> Are the summaries in the [released tags](https://github.com/Materials-Consortia/OPTIMADE/releases) sufficient, or should we make a changelog file containing them too?

Good point. Summaries in released tags are not visible outside the GitHub (I mean they don't come with the source), so I would prefer having them in a changelog file too.

**Comment by merkys** [comment]
Changelog is already present in the source (:partying_face:), closing the issue.
