### ISSUE TITLE
References attribute "type"

### ISSUE THREAD

**Issue by CasperWA** [Materials-Consortia/OPTiMaDe#200]
For filter querying, it is a problem that we allow reference entries to have an attribute called `type`, which is equal to the BibTeX meaning of `type`.

This should either be changed to `bib_type` (or similar) or not be supported at all, as it clashes with the existing "top-level" `type` field that resources MUST have.

**Comment by merkys** [comment]
Do they really clash? AFAIK, we don't allow queries on entry types, thus filter should not even pay attention to "top-level" `type`.

**Comment by CasperWA** [comment]
> Do they really clash? AFAIK, we don't allow queries on entry types, thus filter should not even pay attention to "top-level" `type`.

Ah - I thought one could query all attributes _and_ `"id"` and `"type"`?

**Comment by rartino** [comment]
Aside the question about filters, for other response types, it may not even be possible to represent them at different levels in the output. So, I agree this is a specification bug.

**Comment by merkys** [comment]
I think I got the point.

Maybe this could be solved by dropping query support for `type` (meaning the entry type)? Current design seemingly postulates the homogeneity of lists of entries, as both entry listing endpoints and relationships will contain entries of the same type, and the type is easily inferrable.

If not, we'll have to rename `type` (meaning BibTeX reference type), as @CasperWA suggests.

**Comment by CasperWA** [comment]
> Maybe this could be solved by dropping query support for `type` (meaning the entry type)? Current design seemingly postulates the homogeneity of lists of entries, as both entry listing endpoints and relationships will contain entries of the same type, and the type is easily inferrable.

For completion, the query support should also be dropped for `id` then, in my opinion. In this way _only_ `attributes` are queryable.
Is there a need to query for `id`'s?

However, concerning @rartino's comment:
> Aside the question about filters, for other response types, it may not even be possible to represent them at different levels in the output. (...)

It seems that we can _never_ have _any_ attribute named as `id`, `type` or any other attribute.
This would indeed also create problems for the `response_fields` filtering.

**Comment by merkys** [comment]
I am becoming more convinced that we should think of `id`, `type` and the attributes as belonging to the same namespace. While we could in principle forbid filtering on `id` and `type`, and make them non-filterable by `response_fields` (mandating that `id` and `type` must always be present in the output), I'm not sure if this is worth the hassle.

> For completion, the query support should also be dropped for `id` then, in my opinion. In this way _only_ `attributes` are queryable.
> Is there a need to query for `id`'s?

I guess so. For example we want to find all the structures from Marsh 2009 paper, thus we'd query for
```
/structures?filter=references.id="Marsh2009"
```

So let's probably just rename `references` attribute `type` to `bibtype` for now, and think of how to express the namespace merge.
