### ISSUE TITLE
Definition of `data_available`

### ISSUE THREAD

**Issue by CasperWA** [Materials-Consortia/OPTiMaDe#208]
This is very minor. But I have found that the COD implementation utilizes the definition of `data_available` that I had originally thought was the intent, however, after reading the spec through, which states: `data_available: an integer containing the total number of data objects available in the database.`, I have found that this should actually be a static number for each endpoint.
The COD implementation (and my own original understanding) is that `data_available` shows the total number of resources that matches the current filtered resources, i.e., it can easily be used for pageing, etc.
So which is it?

In the end, I would indeed like a `meta` field for each of the cases above. The second need only be present when a filter is applied.

**Comment by merkys** [comment]
Well spotted. IMO, we have three related concepts:

1. Total number of entries of a particular entry type. This is static in a sense that this number does not depend on query parameters.
2. Number of entries matching a particular query, regardless of pagination parameters.
3. Number of entries returned in `data` payload, of a possibly paginated response.

Reading the specification now I understand that `data_available` matches 1), and `data_returned` matches 2). There seems to be little need to have a field for 3), as number of entries in `data` payload can be easily found out.

This makes the current COD implementation (v0.4.1) incorrect. Nevertheless, the specification could be amended a little to stress that `data_returned` is independent of pagination parameters.

**Comment by CasperWA** [comment]
I agree with your assessment @merkys and will update my own implementation accordingly, since I have mixed up the definition of `data_returned` (thought it was 3, but it should indeed be 2, as you state). So concerning your comment:

> (...) Nevertheless, the specification could be amended a little to stress that `data_returned` is independent of pagination parameters.

I completely agree, and I will make a PR trying to clarify this.

**Comment by CasperWA** [comment]
I have another edge case:
What do we mean by "query parameter" concerning point 2)?
I.e., if I have `page_offset` as a parameter, should `data_returned` also take this parameter into account? Or should it _only_ consider all parameters that are _not_ related to pagination, i.e. that do not start with `page_`?

**Comment by merkys** [comment]
> What is understood by "query" or "query parameters" concerning point 2)?
> if I have `page_offset` as a parameter, should `data_returned` also take this parameter into account? Or should it _only_ consider all parameters that are _not_ related to pagination, i.e. that do not start with `page_`?

By **query** I meant `filter` query parameter, and with **pagination parameters** - query parameters starting with `page_`. Thus the dependency table (:heavy_check_mark: means dependency):

| Field | Entry type | Filter | Pagination parameters |
|---|---|---|---|
| `data_available` | :heavy_check_mark: | | |
| `data_returned` | :heavy_check_mark: | :heavy_check_mark: | |
| No. of entries in `data` | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |

**Comment by merkys** [comment]
Fixed the COD implementation in v0.4.2, rolled out today.
