### ISSUE TITLE
Exclusion of 'id' and 'type' properties upon request

### ISSUE THREAD

**Issue by merkys** [Materials-Consortia/OPTiMaDe#209]
The specification allows exclusion of `id` and `type` properties upon request. Although having no "special" properties sounds nice, JSON response without `id` and `type` is invalid according to JSON API specification. Moreover, I cannot think of a use case when the output without `id`and `type` would be beneficial. Shall we define `id` and `type` attributes as mandatory regardless the value of `response_fields`?

**Comment by rartino** [comment]
Oh, right, good point.

Given that we now have very few 'default' fields, I've been thinking about changing the definition of `response_fields` to be "which non-default fields do you want to be included" and thus provide no mechanism of avoiding any default ones. Then `id` and `type` wouldn't need any special treatment. And I think from a user perspective this would be nicer.

**Comment by merkys** [comment]
Sounds great. It should really be more intuitive.
