### ISSUE TITLE
Correct how the all endpoint is specified (or remove it completely from the specs)

### ISSUE THREAD

**Issue by rartino** [Materials-Consortia/OPTiMaDe#21]
What does the /all endpoint presently return?

Without a filter it should return all entries of all entry types, using the jsonapi 'type' member to specify which entry_type each record is.

So, e.g.,
```
   /all?filter=id="_exmpl_42"
```
Looks for any entry in the database with the id _exmpl_42, regardless of which type it is.

**Comment by rartino** [comment]
I don't see a major reason to duplicate functionality between the all endpoint and just using an endpoint that specifies entry type, e.g.,
  /structures/?filter=chemical_formula="H2O"
So, my suggestion is to go with specifying an All entry type for all records in the database and return this.

**Comment by rartino** [comment]
Old attempt at specification (new one in first comment):
What does the /all endpoint presently return?

Two alternatives have been proposed to resolve this problem.

* "All" entry types which encompass all data in the database. The All entry type would then only have the 
   following properties:
   - Id                      (e.g., "exmpl_42")
   - creation_date   (e.g., "2018-06-14")
   - entry_type        (e.g., "structure")

* One must specify and entry type, e.g.:
   ```
   /all?filter=id="_exmpl_42";entry="structures"
   ```
   This would then return a structure type entry.

* One could also consider allowing both, i.e., all entry type if no entry type is specified.

**Comment by rartino** [comment]
Approved as specified in top issue description.

**Comment by giovannipizzi** [comment]
We're discussing now at the Optimade meeting that maybe, if we are not sure how the `/all` endpoint should be used, we should just remove this from the specs for now.
