### ISSUE TITLE
Update website

### ISSUE THREAD

**Issue by rartino** [Materials-Consortia/OPTIMADE#225]
I note that the front page still contains the old "logotype" and looks a bit dated. We might want to prepare a new version for the v1.0 release.

**Comment by mkhorton** [comment]
Perhaps a stupid question, but I'm not sure I understand the capitalization
of "OPTiMaDe"?  "MaDe" is presumably "Materials Design", but I don't see
how "OPTi" comes from "Open Databases Integration." Was there ever a
discussion of just using "Optimade" (an "Optimade API") for simplicity, and
forgoing the intercaps?

**Comment by rartino** [comment]
@mkhorton Indeed there was, please post your comments/questions about this to issue #193 instead.

**Comment by mkhorton** [comment]
Ah, I see. Thanks @rartino

**Comment by blokhin** [comment]
@rartino should this be closed?

**Comment by ml-evs** [comment]
Yes, let's close this. The website could still use some love over at https://github.com/Materials-Consortia/materials-consortia.github.io
