### ISSUE TITLE
ASCII vs. Unicode

### ISSUE THREAD

**Issue by CasperWA** [Materials-Consortia/OPTIMADE#237]
This was raised in PR #230. Below is a quote from originating from me, answered by @merkys and finally responded to again by me.

> > A thought: Is there a reason why we use ASCII references and not UNICODE references here? Wouldn't UNICODE make more sense, or?
> 
> My (personal) reasons:
> 
> 1. It's a little bit easier (for a human) to recognize and operate with ASCII references, as they don't transcend single byte limit, and correspond exactly to the value of the byte;

Don't know enough about this to say either for or against this claim.
But in the end, it's a machine encoding language, right? So if it's more readable if it says an ASCII code or Unicode code here should be the same for a human reading it, or?

> 2. We're not using Unicode references in this section (document?), thus there is little need for a switch here.

True. Maybe this issue should be raised in a separate issue, where it can be discussed? And have the possibility for a separate future PR.

As far as I know, Unicode is the main basis for most web-based platforms at this point. However, this is not my field of expertise, it is merely what I think to have gleaned from experience and periphery knowledge aka. it's something I'm more or less claiming without reference here 😅

_Originally posted by @CasperWA in https://github.com/Materials-Consortia/OPTiMaDe/pull/230#issuecomment-568533253_

**Comment by rartino** [comment]
So the concrete suggestion in relation to the specification is that we should say "Unicode symbol U+0022" instead of "ASCII symbol 0x22 hex"? It doesn't make much difference, but I suppose it makes sense now that almost all systems have adopted unicode.

**Comment by sauliusg** [comment]
> So the concrete suggestion in relation to the specification is that we should say "Unicode symbol U+0022" instead of "ASCII symbol 0x22 hex"? It doesn't make much difference, but I suppose it makes sense now that almost all systems have adopted unicode.

I think there is absolutely no sense in changing this. ASCII references serve as unambiguous character designators; what is the *problem* we are trying to re-type them as Unicode code points? For the first 128 code points, Unicode codes are the same as ASCII!

NB: we are not specifying here how the transport of the text happens, i.e. whether the connection will use 7 bit, 8 bit, UTF-8, UCS2 or whatever other encoding. In all cases character reference stays the same.

NB[2]: I would be very septic about changing the specs just for the changing sake, or to become "modern". ASCII is the simplest common denominator; if you do not need the full power of Unicode, why bother mentioning it? Are you very eager to deal with normalisations issues, canonical equivalence, surrogates and all that stuff? There is no need for this in the structuring (JSON) layer (its just lain ASCII), and in the strings, which *are* utf-8, we should refer to the Unicode standard as much as possible, that is where it make sense.

**Comment by merkys** [comment]
> NB: we are not specifying here how the transport of the text happens, i.e. whether the connection will use 7 bit, 8 bit, UTF-8, UCS2 or whatever other encoding. In all cases character reference stays the same.
> 
> NB[2]: I would be very septic about changing the specs just for the changing sake, or to become "modern". ASCII is the simplest common denominator; if you do not need the full power of Unicode, why bother mentioning it?

I second @sauliusg's opinion. Unicode here seems as overcomplication to me.

**Comment by rartino** [comment]
@CasperWA: Trying to clean up the open issues: can we close this? It seems this started as a weak suggestion to change to Unicode, which received a strongly-opinionated rebuttal. Unless someone who feels strongly about changing it takes up the discussion, I think we should close this.

**Comment by CasperWA** [comment]
In the spirit of not overcomplicating things, this can be closed.
If you landed here, and feel strongly that this should be changed, please open a new issue on the topic.

**Comment by rartino** [comment]
(Why a new issue? Why not re-open this one?)
