### ISSUE TITLE
Adoption of json schemas and continous integration

### ISSUE THREAD

**Issue by rartino** [Materials-Consortia/OPTIMADE#25]
Build json schemas (or Nomad meta info schemas) for OPTIMaDe, and implement verification / continuous integration.

**Comment by merkys** [comment]
JSON schemata for v0.9.5 are prepared in [Materials-Consortia/API](../../API).

**Comment by rartino** [comment]
So, the concrete suggestion here is to:
* Adopt these schemas as the official schemas for OPTIMaDe API.
* As such, include them in the OPTIMaDe repository alongside the specification.

**Comment by merkys** [comment]
The OPTiMaDe specification mandates the adherence of its response format to the JSON API. So first of all the responses should be validated against [JSON API schema](https://jsonapi.org/faq/#is-there-a-json-schema-describing-json-api).

**Comment by rartino** [comment]
Good progress on this is being done in the Materials-Consortia/optimade-python-tools repository. Also the Materials-Consortia/python-optimade-candidate-reference-implementation repo has a jsonschema_validator branch with a validator (`validate_url.py`) that runs a schema validation on an OPTiMaDe implementation.

But as far as I know, the work isn't yet complete, and so this issue should remain open until there is "complete" schema checked into the main OPTiMaDe repo.

**Comment by rartino** [comment]
We did check in a schemas in the main repository in #242, #248, and there now exist a validator in optimade-python-tools. I propose we can close this issue, we have "adopted schemas" now. @merkys, @CasperWA, do you agree?

**Comment by merkys** [comment]
Yes, this indeed seems to have been achieved.

**Comment by CasperWA** [comment]
See @rartino's [comment above](https://github.com/Materials-Consortia/OPTIMADE/issues/25#issuecomment-643833701).
