### ISSUE TITLE
Should `include` be part of the single entry URL query parameters?

### ISSUE THREAD

**Issue by CasperWA** [Materials-Consortia/OPTiMaDe#251]
Currently, only `response_fields`, `email_address`, and `response_format` are part of the single entry URL query parameters.

**Comment by merkys** [comment]
Good point. JSON API says

> An endpoint **MAY** also support an `include` request parameter to allow the client to customize which related resources should be returned.

An *endpoint* is then defined quite vaguely, but I assume it to be a *collection*, or a *type* of resources. Therefore, it does not seem to apply to single entries, but I think it might be useful to limit the types of returned related resources.

**Comment by CasperWA** [comment]
I agree. Indeed, it would be nice to have control of the included resources returned for a single-entry as well.
I vote for adding `include` as a query parameters that MAY optionally be implemented for single-entry endpoints and write it explicitly in the spec.

**Comment by merkys** [comment]
> I vote for adding `include` as a query parameters that MAY optionally be implemented for single-entry endpoints and write it explicitly in the spec.

+1. I reached the same conclusion in the other JSON API-ish project I'm working on :)
