### ISSUE TITLE
Definition of query string parameters without values

### ISSUE THREAD

**Issue by CasperWA** [Materials-Consortia/OPTIMADE#259]
The query string is quite loosely defined in [RFC3986](https://tools.ietf.org/html/rfc3986#section-3.4), and I was wondering what our convention is on how to handle query parameters with empty values.

To take an explicit example, let's look at `include`.
Already we state that `A query with the parameter include set to the empty string means no related resource objects are to be returned under the top-level field included.`
I take this to mean a URL like `https://example.org/v1/structures?include=""` ~or `https://example.org/v1/structures?include=''`~.
But how about `https://example.org/v1/structures?include=`? Or even `https://example.org/v1/structures?include`?

In `optimade-python-tools`, we've currently implemented the understanding that `include=""` ~or `include=''`~ are different from `include=`, i.e., the latter will be considered equivalent to the default - as if the `include` parameter was not explicitly written in the URL at all. But maybe this is incorrect?
Indeed, with the updated dependencies for the `requests` library and the framework we built the server upon (FastAPI), it now seems `include=` is parsed differently and considered equal to `include=""` ~or `include=''`~.

As a bonus, what may then be understood by `/structures?include`? Should it mean to include all the different `relationships` available, or rather equivalent to passing an empty string? Or should it not be allowed altogether?

**Comment by merkys** [comment]
I have expected [RFC3986](https://tools.ietf.org/html/rfc3986#section-3.4) to be less vague concerning query strings. However, I don't have a better reference, thus I'll only speak from my personal experience.

In context of HTML forms, I find convenient treating `parameter=` as if `parameter` was not given at all. Empty text fields in HTML forms are passed as `parameter=` thus carrying both "the user has not provided a value for this field" and "the user has provided an empty string value" meanings. But this is the price to pay when one does not have a control over which parameters are sent and which are not.

However, `parameter=""` does not seem elegant to me. The user has to know about this special exception and put `""` in text fields in HTML forms.

Nevertheless, if we do not care about HTML forms much, I would suggest assigning `parameter=` the meaning of an empty string, and no `parameter` the meaning of an undefined value.

**Comment by rartino** [comment]
From where does the idea come that quotation marks in query parameter values would carry any special meaning beyond what the API defines for those query parameters? Is there actually anything in RFC3986 that can be interpreted to say this?

My present understanding of our specification is that `include=` sets `include` to an empty string. `include=""` sets include to two double quotes (which presumably is not valid input and should generate an error). And the behavior of `include` without `=` is not defined (so, it would be best if it reports an error.)

But I agree with @merkys that there is a somewhat valid concern here in that it may be a mistake in defining "the query parameter is present but empty" as having a different behavior from "the query parameter is not present". As @merkys points out, when dealing with HTML forms, it is a *bit* of a hassle to allow user input to generate the second option. But I also agree with @merkys conclusion; the behavior of raw HTML forms have very little relevance here, so why would we care about this?

**Comment by CasperWA** [comment]
Thanks for the inputs. From both @merkys' and @rartino's answers, is it then correct to state the following:

`parameter=` means "the user has provided an empty string value"
`parameter` means "undefined from the OPTiMaDe spec point-of-view - return error if `parameter` is is a valid query parameter"
`parameter=value` means "the user has provided the value `value` for `parameter`"
`<empty>` means "the user has not provided a value for the `parameter`, use default value"

The distinction between the latter and the first are important according to `include`, since it's the difference between having `include` default to `include=references` or not.

**Comment by rartino** [comment]
@CasperWA Can we close this? I think we have concluded that it is OK to define a difference between `include=` and leaving out `include`? And that the specification is OK in this respect?

**Comment by CasperWA** [comment]
This has been resolved and reflected also in the `optimade-python-tools` through Materials-Consortia/optimade-python-tools#209
