### ISSUE TITLE
Handling unknown property names in filters

### ISSUE THREAD

**Issue by fekad** [Materials-Consortia/OPTIMADE#268]
If there is a wrong/unknown argument in the filter, it could just simply fail. It is much easier to fix a problem if you know what is the actual problem, rather then just having a weird behaviour.

The [specification](https://github.com/Materials-Consortia/OPTIMADE/blob/develop/optimade.rst#37handling-unknown-property-names) is confusing:
> The rationale for treating properties from other databases as unknown rather than triggering an error is for OPTIMADE to support queries using database-specific properties that can be sent to multiple databases.

I would say if I want to query different databases it is way simpler to create a separate one for each database rather than include all the proper database-specific property name into a single one.

Weird cases:
- The following example is very dangerous as well:
  `filter=_exmpl1_bandgap<2.0 OR _exmpl2_bandgap<2.5`
  In theory, this filter will return with ALL of the data if `_exmpl1_bandgap` or `_exmpl2_bandgap` are not defined. 
- Using a wrong/misspelt parameter the database will return with the all of the entries:  https://dev-aiida-dev.materialscloud.org/autowannier/optimade/v0/structures?wrong_field=any_random_value

**Comment by rartino** [comment]
This topic was brought up here: #92 and the present behavior got implemented in: #162.

First, the behavior you see in materialscloud is a bug. The specification says that a filter involving an unknown propery without a database prefix, e.g. `wrong_field` MUST issue `400 Bad Request` with a message indicating the offending property name.

About the case with database prefixes, the rationale to not simply break with an error for unknown properties when they have a foreign database prefix is that such behavior would make a "skyscanner"-like solution that passes your one query onwards to other databases impossible if it needs to involve such properties. (But personally, I was a fairly strong proponent about that properties that are "ignored" this way should always issue a warning, but this was argued against.)

**Comment by fekad** [comment]
@rartino Thank you for pointing me in the right direction! Personally I agree with you to apply more restriction on it. I would simply return with an error because it is way harder to interpret the query in this way. Nevertheless, there was a consensus about it recently, so I close this issue and report the bug on the appropriate forum.
