### ISSUE TITLE
Provenance / Publication references

### ISSUE THREAD

**Issue by rartino** [Materials-Consortia/OPTiMaDe#27]
OPTIMaDe needs to provide some facility to communicate data provenance.

Specifically, some data provenance property needs to facilitate the aggregation of OPTIMaDa IDs (i.e., database prefix + local id) and other ids.

Dates?

Publications?

**Comment by rartino** [comment]
Jsonapi allows to return a `relationships` field alongside `data` (which contains the returned records) that is more or less meant for this, see, e.g., http://jsonapi.org/format/#fetching-relationships

A proposal is thus to include a field per record in `data` that references (by index, or perhaps string) a record in relationships which contains the provenance data. It is in particular important that the provenance record can supply different provenance data (e.g., publicatons) for different properties *in the same record*.

(This came up from some discussion with Fawzi and Cormac)

**Comment by rartino** [comment]
So, the concrete suggestion is to make the above mechanism optional, with the following format:
```
{
  ... <other response items> ...
  "data": [
    {
      "type": "structure",
      "id": "example.db:structs:0001",
      "attributes": {
        "chemical_formula": "Es2O3",
        "local_id": "example.db:structs:0001",
        "url": "http://example.db/structures/example.db:structs:0001",
        "immutable_id": "http://example.db/ids/structs/0001@123",
        "last_modified": "2007-04-05T14:30Z"
      },
    "relationships": {
      "references": {
        "links": {
          "self": "http://example.com/structures/example.db:structs:0001/relationships/references",
          "related": "http://example.com/structures/example.db:structs:0001/references"
        },
        "data": [{ "type": "reference", "id": "9" }, { "type": "reference", "id": "42" }]
      }
    },
   ....
  ],
  "included": [{
    "type": "reference",
    "id": "9",
    "attributes": {
            "id": "ITEM-1",
            "itemData": {
                "id": "ITEM-1",
                "issued": {
                    "date-parts": [
                        [
                            "2007"
                        ]
                    ]
                },
                "title": "My paper",
                "type": "journal-article"
            },
            "locator": "21",
            "label": "page",
            "uris": [
                "http://www.mendeley.com/documents/?uuid=970e7ce0-8a21-482e-b7d6-e77794a2d37d",
                "http://www.zotero.org/uniqueDocumentId"
            ]
    }, 
    "links": {
      "self": "http://example.com/references/9"
    }
  ...
  }]}
```
And, we also need a new reference entry type. The suggestion is to use this schema:
https://github.com/citation-style-language/schema/raw/master/csl-citation.json

Also, the above handles references. Do we also need an actual provenance field that tracks a log of things that have happened with the entry?

**Comment by dwinston** [comment]
This is not a comment on the concrete suggestion above, but only to provide a link to prior art for consideration. This is how Materials Project encodes provenance of structures: [pymatgen.util.provenance.StructureNL](https://github.com/materialsproject/pymatgen/blob/v2018.6.11/pymatgen/util/provenance.py#L174), a structure notation language.

**Comment by merkys** [comment]
> And, we also need a new reference entry type. The suggestion is to use this schema:
> https://github.com/citation-style-language/schema/raw/master/csl-citation.json

To me CSL seems very basic. I prefer [BibTeX format](http://www.bibtex.org/Format/) which seems to be widely used and supported. Convention of representing BibTeX in JSON exists as [BibJSON](http://okfnlabs.org/bibjson/) (just stumbled upon it).
