### ISSUE TITLE
Centralized server

### ISSUE THREAD

**Issue by rartino** [Materials-Consortia/OPTIMADE#29]
Should OPTIMaDe provide a centralized server to aggregate all OPTIMaDe-supporting databases?

* This correlates with the discovery mechanism in #22, but it is likely good to provide both.
* An aggregator could be implemented via OPTIMaDe API itself, which aggregates all
  sibling servers it knows about. This would be useful even outside a "web interface". But, then the website could simply query that API point.

**Comment by blokhin** [comment]
Does it have something in common with the OPTIMaDe-_Skyscanner_ idea?

**Comment by rartino** [comment]
I think so? Is there something in an "OPTIMaDe-Skyscanner" idea that isn't covered in the description above?

**Comment by blokhin** [comment]
The first prototype is now live at https://optimade.science
