### ISSUE TITLE
Clarify api_version in response specification

### ISSUE THREAD

**Issue by ml-evs** [Materials-Consortia/OPTIMADE#292]
Currently the `api_version` field is described in two places:

- [Section 4.2](https://github.com/Materials-Consortia/OPTiMaDe/blob/develop/optimade.rst#json-response-schema-common-fields) as:
  > **api_version**: a string containing the version of the API implementation.

- [Section 5.3.1](https://github.com/Materials-Consortia/OPTiMaDe/blob/develop/optimade.rst#base-info-endpoint) as:
  > **api_version**: Presently used version of the OPTIMADE API.

Could we make this stricter? basically matching the `version` field of `available_api_versions`, i.e.

> **version**: a string containing the full version number of the API served at that versioned base URL. The version number string MUST NOT be prefixed by, e.g., "v".

Happy to make the PR if people agree. We've just started validating this field with a semantic version type in optimade-python-tools.

Tagging @CasperWA we had already discussed it.

**Comment by rartino** [comment]
I very much agree to squeeze this in between v1.0.0-rc.2 and v1.0.0 proper! The 'v' prefix should now only be used in two places: in the URL path segment for versioned URLs, and in the proposed `api_hint` parameter of #290.

**Comment by rartino** [comment]
So, I think these are now addressed within #298?, right?
