### ISSUE TITLE
Update schemas for v1.0.0 

### ISSUE THREAD

**Issue by rartino** [Materials-Consortia/OPTIMADE#294]
Assuming we will merge #290 soon, this will require some form of adjustment of the schemas, since it allows serving of the API also under the unversioned base URL.

I see that the present schemas specify the paths below the unversioned base URL in the schemas, e.g. `/v1/info`. The problem is, as we release new versions, all versioned endpoints will all use their own schemas, and it will be up to the implementation to mix-and-match API versions as one wants.
 
Hence, would it not make sense to use relative URLs, relative to where an API of version X is served? I.e., so just replace `/v1/info` -> `/info` in the present schema files?

Then an implementation that serves `v1.1` on the unversioned URL, but `v1.2` under `/v1/` and `v1.0` under `/v1.0/` just needs to reference the correct schemas everywhere and all will be good.

**Comment by rartino** [comment]
@CasperWA @ml-evs Two questions to you:
- Would it break anything if we just remove all versioned URL path segments from the schemas?, e.g., `/v1/info` -> `/info`, `/v1/info/{entry}` -> `/info/{entry}`? This matches the picture given by the `meta` filed `query`->`representation` where we have said to use the *unversioned* path. 
- Do you agree that it makes sense to setup `https://schemas.optimade.org/openapi/v1.0/schema.json` (or similar?) as a permanent URL for our schemas? Because in that case we need to petition @gmrigna to trouble his system administrators once more. Should we perhaps even try to serve it out of the main OPTIMADE repo?... (It is possible if we setup a `/docs` directory to serve with github pages...)

**Comment by ml-evs** [comment]
>     * Would it break anything if we just remove all versioned URL path segments from the schemas?, e.g., `/v1/info` -> `/info`, `/v1/info/{entry}` -> `/info/{entry}`? This matches the picture given by the `meta` filed `query`->`representation` where we have said to use the _unversioned_ path.

Shouldn't do, this is only added in our server code, so generating the schemas without the versions is pretty trivial. I could even add these unversioned schemas directly to #290?

>     * Do you agree that it makes sense to setup `https://schemas.optimade.org/openapi/v1.0/schema.json` (or similar?) as a permanent URL for our schemas? Because in that case we need to petition @gmrigna to trouble his system administrators once more. Should we perhaps even try to serve it out of the main OPTIMADE repo?... (It is possible if we setup a `/docs` directory to serve with github pages...)

For post-1.0 versions, I would agree, yes. We have discussed how we can accommodate versioning of schemas and models from within optimade-python-tools, but at the moment the solution is just to rollback to previous versions of the package... I would support hosting different schema versions from this repo, or a separate one.

**Comment by rartino** [comment]
> Shouldn't do, this is only added in our server code, so generating the schemas without the versions is pretty trivial. I could even add these unversioned schemas directly to #290?

Add or *change*? I.e., do you suggest having both versioned and unversioned schemas? My suggestion is that we *only* provide the schemas for unversioned paths in the main repo and declare that you are supposed to validate against the same path that you put in `meta`->`query`->`representation`. Would this mess with any automatic OpenAPI validation tools? Or can you choose yourself what counts as the "root" of the path when you ask for a validation?

>> Do you agree that it makes sense to setup https://schemas.optimade.org/openapi/v1.0/schema.json (or similar?) as a permanent URL for our schemas?
> For post-1.0 versions, I would agree, yes. We have discussed how we can accommodate versioning of schemas and models from within optimade-python-tools, but at the moment the solution is just to rollback to previous versions of the package... I would support hosting different schema versions from this repo, or a separate one.

Why only post-1.0? Why not set up that permanent path *now* and put our v1.0 schema there when we release v1.0.0?

**Comment by ml-evs** [comment]
> Add or _change_? I.e., do you suggest having both versioned and unversioned schemas? My suggestion is that we _only_ provide the schemas for unversioned paths in the main repo and declare that you are supposed to validate against the same path that you put in `meta`->`query`->`representation`. Would this mess with any automatic OpenAPI validation tools? Or can you choose yourself what counts as the "root" of the path when you ask for a validation?

Change! The validator doesn't use the openapi schema directly, instead it uses the underlying python models that were used to create the schema, so it will happily validate any URL. The only change we need to make is extra validation for `/versions` on the unversioned URL.

> Why only post-1.0? Why not set up that permanent path _now_ and put our v1.0 schema there when we release v1.0.0?

Also agree, by post-1.0 I meant 1.0 and beyond (as it would be tricky for us to generate e.g. `0.9`, `0.10` schemas of the same quality as our current schema).

**Comment by rartino** [comment]
@gmrigna So, would it be OK to trouble your sysadmins with one final DNS setting? (Perhaps we should offer to buy them a cup of coffee or something? :-) ) At least I think this one should be the last one from me for a while.
```
schemas.optimade.org. CNAME materials-consortia.github.io
``` 
So that we can setup permanent URLs for the OPTIMADE schemas at: https://github.com/Materials-Consortia/schemas

**Comment by gmrigna** [comment]
host schemas.optimade.org
schemas.optimade.org is an alias for materials-consortia.github.io.
materials-consortia.github.io has address 185.199.108.153
materials-consortia.github.io has address 185.199.111.153
materials-consortia.github.io has address 185.199.109.153

Is this OK?

**Comment by rartino** [comment]
@gmrigna Perfect! The non-ssl links are already working:
  http://schemas.optimade.org/openapi/v1.0/optimade.json
and here github should have no problem obtaining an SSL certificate for us.
