### ISSUE TITLE
Chemical composition and chemical formula

### ISSUE THREAD

**Issue by rartino** [Materials-Consortia/OPTiMaDe#31]
How do we represent chemical composition and chemical formulas in OPTIMaDe?

**Comment by rartino** [comment]
Present suggestion from the group looking at this:

* Any database that works with collections of atoms should be able to provide:  
  - `elements`: A ‘list’ of elements.
  - `element_ratios`: A ‘list’ of corresponding ratios as floating point numbers (0-1] or?: [1-infinity)

* To provide a `chemical_formula` property the only question is then “what do you multiply the ratios
   with?”

* After long discussions... there is no single definition of `chemical_formula` that deduces it from 
  structural information to get something acceptable and sufficient for all users in all contexts. 
  (Molecular crystals, fractional occupations, ...) "It would be good if `chemical_formula` can mean what
  chemists normally mean by chemical formula.”* - but this depends on, e.g.,
  interpretations of bonding physics and to some extent context.

* We see no way out other than:
  
    - Rely on `elements` and `ratios` as the primary canonical attribute for this.
    - Make `chemical_formula` a *required* property defined as: a concatenation of the elements and
      ratios, with all ratios multiplied by some constant. The constant is not specified by OPTIMaDE, but
      should be chosen by the database to be as useful as possible within the context of the database.

* If we allow querying on `chemical_formula` we then give up the principle of only allowing queries on canonical data.

* We need to specify how to handle numerical accuracy on the floating point numbers that are concatenated in the chemical_formula string.

**Comment by davidwaroquiers** [comment]
I would force the sum of element_ratios to be 1.0, such that you can then search for e.g. I want at least 20% of iron.

**Comment by rartino** [comment]
Here is a concrete suggestion:

One arrives at `ratios` like this:
1. Look at the structural description (#23) at find the occurrences of each element *without* considering the features for fractional occupancy (occupancies and assemblies)
2. Normalize the coefficients by gcd
3. If any occupancies are set to = 0, that is interpreted as representing a vacancy site, and that occupancy is treated as = 1 in the following.
4. Adjust the resulting coeffients to account for fractional occupancy *without* renormalizing the total weights.
5. What you arrive at is the `ratios` field.

Then we have a required `chemical_formula` which is a concatenation of the element symbols and the ratios multiplied by an optional constant factor. Fractional coeffients are rounded to four decimal places.

We can optionally include a required `formula` to be a concatenation of the element symbols and the ratios without the optional constant factor. Fractional coefficents are rounded to four decimal places.

**Comment by sauliusg** [comment]
"multiplied by some constant" – This constant is in fact the N/Z (where N is a multiplicity of a geeral position and Z is a number of formula units per unit cell...)

**Comment by rartino** [comment]
Accepted as far as the ratios property and elements property, with ratios summing to 1.

Further work necessary to provide alternative arrays of composition that make more sense for other type of queries.
