### ISSUE TITLE
Swagger OpenAPI validator yields an error

### ISSUE THREAD

**Issue by blokhin** [Materials-Consortia/OPTIMADE#314]
See https://validator.swagger.io/validator/debug?url=https://raw.githubusercontent.com/Materials-Consortia/OPTIMADE/develop/schemas/openapi_schema.json

Sorry if already known.

**Comment by ml-evs** [comment]
Do you know why it might fail in your link (which contains "debug"), but seems to validate fine in the GUI version (unless I'm missing something)? 

https://validator.swagger.io/?url=https://raw.githubusercontent.com/Materials-Consortia/OPTIMADE/master/schemas/openapi_schema.json

**Comment by ml-evs** [comment]
Just a heads-up that we've fixed this upstream at https://github.com/Materials-Consortia/optimade-python-tools/pull/480 

(see e.g. https://validator.swagger.io/validator/debug?url=https://raw.githubusercontent.com/Materials-Consortia/optimade-python-tools/master/openapi/openapi.json).

We should prepare a PR for this repo fairly soon that updates the schema according to our changes since the 1.0 release.

**Comment by blokhin** [comment]
@ml-evs Matthew, should the [main schema](https://raw.githubusercontent.com/Materials-Consortia/OPTIMADE/master/schemas/openapi_schema.json) be also PR-ed?

**Comment by blokhin** [comment]
There are still validation errors: https://validator.swagger.io/validator/debug?url=https%3A%2F%2Fraw.githubusercontent.com%2FMaterials-Consortia%2FOPTIMADE%2Fmaster%2Fschemas%2Fopenapi_schema.json

**Comment by ml-evs** [comment]
These are all fixed on develop (and the schemas are now checked against this URL in the CI), and will be fixed on master when we decide to do a v1.0.1 release (or if we decide to reorganise our branches following #340).

https://validator.swagger.io/validator/debug?url=https%3A%2F%2Fraw.githubusercontent.com%2FMaterials-Consortia%2FOPTIMADE%2Fdevelop%2Fschemas%2Fopenapi_schema.json

**Comment by blokhin** [comment]
@ml-evs is there any update on that?

PS my motivation is https://github.com/APIs-guru/openapi-directory/issues/722

**Comment by ml-evs** [comment]
Hi @blokhin, the schemas have been fixed for a while now, we just haven't pushed to master as it is meant to be reserved for releases only. Once #351 is merged the link to master should work fine (still waiting on some reviews of blocking PRs; hopefully by the next workshop we will have 1.0.1...)

**Comment by ml-evs** [comment]
Closed by the v1.1 release (#365)!
