### ISSUE TITLE
Publish releases to Zenodo

### ISSUE THREAD

**Issue by ml-evs** [Materials-Consortia/OPTIMADE#318]
We should consider publishing each release of this repository on Zenodo with their GitHub integration. Various papers are beginning to mention OPTIMADE, and until the main paper is out, Zenodo can provide a citeable record. I imagine we all have the permissions to do this as admins of Materials-Consortia, I'm happy to do it if we think it's a good idea...

**Comment by ml-evs** [comment]
This was discussed in the call today, and whilst there was broad agreement that we should do this, the issue of authorship was raised. I'm going to investigate if we can provide a custom author list (from e.g. the CONTRIBUTING file) for the Zenodo record via their GitHub integration, otherwise we may need to manually make releases to Zenodo.

**Comment by mkhorton** [comment]
Hi @ml-evs, would it be possible to add myself to the `AUTHORS` list in this repo from the MP side? Thanks.

**Comment by ml-evs** [comment]
> Hi @ml-evs, would it be possible to add myself to the `AUTHORS` list in this repo from the MP side? Thanks.

For sure! In fact, I will make a draft PR to update to the `AUTHORS` now, and we can make sure that any additions to the authors of the paper also get added here. I'll only archive once we think that list is complete.

**Comment by ml-evs** [comment]
We needed an OPTIMADE DOI for another project, so I have published v1.0 of this repository on Zenodo. All metadata can be changed pending the authors list updates, for now I have included anyone who has added their ORCID + Affiliation to the google sheet that was sent around.

Please take a look at this interim version and provide feedback (I will raise this more widely once the author list has been finalised)

http://doi.org/10.5281/zenodo.4195051

**Comment by ltalirz** [comment]
Great; I was just reading the draft and going to suggest this.
I'll let Gian-Marco know that this is how the Optimade Standard should be cited in the Draft as well

**Comment by ml-evs** [comment]
I think this is already the case in the paper?

**Comment by ltalirz** [comment]
You're right!
It's just the first reference that points to github (28), the next time it's mentioned it includes the zenodo link.
