### ISSUE TITLE
Registration of Optimade standard on FAIRsharing.org

### ISSUE THREAD

**Issue by ltalirz** [Materials-Consortia/OPTIMADE#324]
The [GO FAIR initiative](https://www.go-fair.org/) has launched an effort to [standardize how data repositories document their implementation of the FAIR principles](https://www.go-fair.org/how-to-go-fair/), both in human-readable and in machine-readable form (a so-called "FAIR Implementation Profile).

Any metadata / API standards included in such a documentation (such as, for example, the Optimade standard) will need to be referenced via a persistent globally unique identifier, and the GO FAIR initiative suggest using the [FAIRsharing.org](https://fairsharing.org/standards/) standards registry.

Since we (Materials Cloud team & others) will participate in the first round of these workshops, we would like to register the Optimade standard on fairsharing.org - I believe this can in any case only be positive, since it is another place to advertise the existence of Optimade.

The [standards registration form](https://fairsharing.org/new/standard) requires us to make a few choices; in particular it asks us to provide one contact name, email and ORCID

This issue is intended as a thread for people to discuss & provide suggestions for this form (will also be mentioned on the mailing list).

**Comment by ml-evs** [comment]
Sounds good to me, I'll be at the workshops you posted too. Do you think an OPTIMADE lightning talk would be appropriate at the main conference?

**Comment by ltalirz** [comment]
Thanks @ml-evs ! 
I haven't received much information about the main symposium, I'll ask the organisers for more info and report it here.

**Comment by ltalirz** [comment]
thanks to @gmrigna for registering the optimade standard on fairsharing.org: https://fairsharing.org/bsg-s001534/

**Comment by gmrigna** [comment]
There is now a DOI assigned: https://doi.org/10.25504/FAIRsharing.xvfqAC

**Comment by gmrigna** [comment]
There is now even a DOI assigned: https://doi.org/10.25504/FAIRsharing.xvfqAC
