### ISSUE TITLE
Travis changing OSS billing

### ISSUE THREAD

**Issue by ml-evs** [Materials-Consortia/OPTIMADE#331]
As you may have seen, [Travis is ending free builds for open source projects](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing). 

As part of the transition, we will get 1000 CI minutes to use before we have to start paying; each push to this repository uses ~3 minutes (as PR and push runs separately), so it will take us quite a while to run this down, but we should think about migrating (presumably to GitHub actions, which is used for part of our CI here already).

**Comment by CasperWA** [comment]
👍 for moving to GH Actions as the solution.

**Comment by ml-evs** [comment]
I think it would be a useful time to add swagger validation of the OpenAPI schemas to this repository too to avoid any errors arising when transferring them over from python-tools, or if we eventually move away from python-tools/need to change something manually.

**Comment by ml-evs** [comment]
This is fixed by #333, which migrated the CI to GitHub Actions, but Travis has been left enabled for a little while just to make sure things are working. Let's keep this issue open until we disable it for good.

**Comment by CasperWA** [comment]
> This is fixed by #333, which migrated the CI to GitHub Actions, but Travis has been left enabled for a little while just to make sure things are working. Let's keep this issue open until we disable it for good.

I'd probably just make the move ASAP. No reason to run both CIs.
What timeline did you have in mind for this though?
