### ISSUE TITLE
New `issue_tracker` field in `meta->provider`?

### ISSUE THREAD

**Issue by CasperWA** [Materials-Consortia/OPTIMADE#337]
In a discussion with @shyamd and @csadorf in CasperWA/voila-optimade-client#215 I suggested to create a field `issue_tracker` in the `provider` JSON object under the top-level `meta` field.
The field would be OPTIONAL.
The value should be a URL, pointing to the provider's issue tracker for their OPTIMADE implementation, e.g., for Materials Cloud the `issue_tracker` value would be https://github.com/aiidateam/aiida-optimade/issues, while for COD it would be https://projects.ibt.lt/repositories/issues (AFAIK, @sauliusg and @merkys can correct me if I'm wrong).

It may be that this field is more relevant under the `implementation` JSON object in the top-level `meta` field, if one has an issue tracker specific to each different implementation from the same provider?

**Comment by merkys** [comment]
Good idea! For the COD the issue tracker is https://projects.ibt.lt/repositories/projects/cod-optimade.

**Comment by merkys** [comment]
> It may be that this field is more relevant under the `implementation` JSON object in the top-level `meta` field, if one has an issue tracker specific to each different implementation from the same provider?

I support adding `issue_tracker` under `meta.implementation`. It's much easier to provide the same tracker URL for different implementations than to think of how to show different tracker URLs for the same provider.
