### ISSUE TITLE
Clarify _exmpl_band_gap vs _exmpl_bandgap lexical examples

### ISSUE THREAD

**Issue by ml-evs** [Materials-Consortia/OPTIMADE#357]
We provide `band_gap` and `bandgap`as two examples for valid property names and filter examples. Whilst they are both valid, this may be confusing to readers, so we should change them (or provide alternative examples).

**Comment by merkys** [comment]
Good catch. While these nonstandard properties are used only in examples, consistency is important in examples too. I would suggest using one of these spellings based on which is more common among people dealing with band gaps.

**Comment by ml-evs** [comment]
> Good catch. 

We have the the paper reviewer to thank!


> While these nonstandard properties are used only in examples, consistency is important in examples too. I would suggest using one of these spellings based on which is more common among people dealing with band gaps.

Yep, I'll prepare a PR later on.
