### ISSUE TITLE
Should the API response include units?

### ISSUE THREAD

**Issue by ltalirz** [Materials-Consortia/OPTiMaDe#36]
As soon as the API responses include physical quantities that have units, we need to decide whether to include these units as part of the response.

 * pros: 
   * including units (from a standardized set) as part of the response makes it possible to avoid (some) unit conversions. 
    * Numbers may be more human-readable by using units adapted to the data in the corresponding entry
 * cons:
   * clients will need to implement unit conversion
   * the schema will be slightly more complicated
   * the size of the response increases

We (Fawzi, Markus, Andrius, Leopold) propose, for the moment, to do the simple thing and **not** include units as part of the response.
Standard units will be defined for all physical quantities. This information will be present in the JSON schema, preferably in machine-readable form.

**Comment by giovannipizzi** [comment]
I agree that for now we decide sensible units and define them in the specification. E.g. in #23 we use angstrom for atom coordinates and cell vectors. Ideally we should always use the same units across the API when sensible

**Comment by merkys** [comment]
> Final task: Make sure that all values that have units in the specs now specify clearly the units, then we can close this issue

Done. Closing the issue.

**Comment by giovannipizzi** [comment]
@merkys does this mean that you checked and all units were already specified?

**Comment by merkys** [comment]
> @merkys does this mean that you checked and all units were already specified?

@giovannipizzi exactly, all seem complete
