### ISSUE TITLE
Use "Symbols" instead of "Names" in the description of the elements field

### ISSUE THREAD

**Issue by JPBergsma** [Materials-Consortia/OPTIMADE#367]
I noticed that in the description of the field elements under the structures endpoint it says:
"**Description**: Names of the different elements present in the structure."
If I, however, look at the example, the symbols of the elements are used, e.g. "Fe", "H", instead of the names, e.g. "Iron", "Hydrogen". I was therefore wondering whether it would be ok to change the description to:
 "**Description**: Symbols of the different elements present in the structure."

**Comment by merkys** [comment]
I agree, "symbols" is a bit more appropriate in this context.
