### ISSUE TITLE
What is the purpose of the calculation endpoint?

### ISSUE THREAD

**Issue by JPBergsma** [Materials-Consortia/OPTIMADE#369]
Currently, there is a "calculations" endpoint in the Optimade Specification.
There is however no description of what the purpose and the properties of the calculation endpoint are, except for one line stating that it has the standard properties that all entry points have. Therefore, I think it would be good to expand the description of the calculation endpoint, and perhaps definitions for a number of fields could also be added, so it becomes easier to search for data that was generated with certain methods. 
As I was not there when the original OPTIMADE standard was written I think it would be better if someone else who knows more about this endpoint expands the description.

**Comment by merkys** [comment]
Please also take a look at #24, some ideas have been expressed there.

**Comment by rartino** [comment]
I'll add that there is indeed a lengthy PR on its way resulting from the big OPTIMADE meeting we had last month that will expand the standardization of the calculations endpoint.

But, I'll also add that the calculations endpoint is useful (and used) today by providing provider-specific data in it.

**Comment by JPBergsma** [comment]
Thanks I Look forward to see that PR!
