### ISSUE TITLE
API response should include reference to schema, to be completed first

### ISSUE THREAD

**Issue by ltalirz** [Materials-Consortia/OPTIMADE#37]
We (Fawzi, Andrius, Markus, Matt, Leopold) propose that the API response should include a reference to  a schema that can be used to validate its responses.

This can include one or two of:
 * a JSON schema
 * a NOMAD meta-info schema

Advantages:
 * machine-readable way for clients to understand the (intended) response format, including custom extensions

Disadvantages:
 * none that we are aware of

**Comment by ltalirz** [comment]
@blokhin Could you please explain your reservations about this point?

**Comment by blokhin** [comment]
@ltalirz I do appreciate this suggestion, just cannot immediately comprehend what are the benefits of choosing the NOMAD's option _vs._ general-purpose JSON schema.

**Comment by ltalirz** [comment]
Ok, I would say this is a separate issue from having a link to a schema in the response.
Obviously the question of which schema to use should be considered carefully, and we did not want to exclude either option during the session. A discussion of the pros and cons of both approaches can be found in the meeting minutes on Google Docs under  *Schema, implementation, and testing routines*

**Comment by blokhin** [comment]
@ltalirz could you post a link to that document? It's not among those two mentioned at the [API repo](https://github.com/Materials-Consortia/API).

**Comment by blokhin** [comment]
OK, received 👍 pity it's not public.

**Comment by kxyyang** [comment]
Would it be possible that API response follow a certain specification ? For example, Citrine Informatics proposed a Materials Information File (MIF) , which is an open JSON-based file format (available at http://citrineinformatics.github.io/mif-documentation ) that we could use. It seems it could be used as a schema for representing the query data output. 

An associated paper , entitled " Materials science with large-scale data and informatics: Unlocking new
opportunities " can be found at MRS BULLETIN • VOLUME 41 • MAY 2016 • www.mrs.org/bulletin .

**Comment by blokhin** [comment]
@kxyyang +1 for MIF/PIF, we do already use it for quite some time to represent physical properties in [our API](https://developer.mpds.io/#JSON-schemata).

**Comment by ltalirz** [comment]
I'm very much in favor of relying on existing standards but the MIF clearly seems tailored towards representing experimentally measured structures. For example, it doesn't seem to have the concept of atomic positions (other than returning a cif file), so it is not clear to me whether it is a good match for optimade at this point.
However, if someone wants to point out specific terms that could easily be aligned between the two formats to avoid confusion, I'm sure this would have widespread support.

**Comment by rartino** [comment]
Perhaps it is a good idea to collect somewhere (the wiki?) a list of already defined output formats / return values / materials science ontologies that one may want to keep an eye on as we try to standardize things for OPTIMaDe? So far I'm aware of:
* The [CIF dictionaries](https://www.iucr.org/resources/cif/dictionaries)
* [Electronic Structure Common Data Format](https://esl.cecam.org/ESCDF_-_Electronic_Structure_Common_Data_Format) 
* [NOMAD Meta Info](https://metainfo.nomad-coe.eu/nomadmetainfo_public/archive.html)
* [Pauling file vocabulary](http://paulingfile.com/index.php?p=crystal%20structures#small%20crystallographic%20vocabulary) and [common terms for phase diagrams](http://paulingfile.com/index.php?p=phase%20diagrams#common%20terms)
* Terms/return values already used in the larger database projects but seemingly defined less stringently than those given above, e.g, Materials project, Aflow, oqmd, materials cloud, etc.
* The ontology that was presented in a talk during one of the later days in the OPTIMaDe workshop. I have some difficulty to find hard info on the Internet, but I found this: [EMMO from EMMC](https://emmc.info/wp-content/uploads/2017/12/EMMC_IntOp2017-Cambridge_Ghedini_Bologna.pdf)?
* And now then [Materials information file](http://citrineinformatics.github.io/mif-documentation )

**Comment by ltalirz** [comment]
@rartino Great suggestion!
Let me mention that there is a newly formed "Semantic Assets for Materials Science" task group in the Research Data Alliance, and their first point of action will be exactly to collect semantic assets (keyword lists, taxonomies, ontologies) from the field of materials science, likely on the [NIST materials registry](https://materials.registry.nist.gov/).
They haven't started yet, though, and there is no reason to wait - once this registry has been established we will simply move our list there.

I've already put your list onto the [wiki](https://github.com/Materials-Consortia/OPTiMaDe/wiki/Semantic-assets-for-Materials-Science), feel free to edit!

P.S. If anyone would like to join the task group, contact [Vasily Bunakov](https://www.scd.stfc.ac.uk/Pages/Vasily-Bunakov.aspx) from the STFC.

**Comment by kxyyang** [comment]
Currently MIF does not support the definition of crystalline structure. But as said " A number of key objects have already been defined to encompass common materials concepts (e.g., materials, measurements, phases, phase diagrams), and new objects can be readily created as needed."  It says we could define new object.  So how about we extend the MIF schema by defining a "crystal structure"  object ? And the definition of this "crystal structure" object could link to what we discussed about defining the crystal SYSTEM at the workshop.

**Comment by kxyyang** [comment]
Citrine Informatics also proposed an Physical Information File (PIF), which is a schema that is designed to impose structure on information about physical systems (http://citrineinformatics.github.io/pif-documentation/index.html).  Not sure whether this support the definition of crystalline structure... Worth investigating.

**Comment by rartino** [comment]
I've started preparing a PR so we can actually link the schema in a reply in a standardized way.

I see two ways we can do this:

### Alternative 1
It turns the upcoming v1.1 of JSON API have adopted an official way to do this in json-api/json-api#1447. They define a new link type for the top level links field:
```json
"links": {
    "describedby": "http://schemas.optimade.org/v1.0.0/structures.json",
}
```
We can allow for this, but technically we are then breaking the JSON API v1.0 specification, which says that we are not allowed to provide any other members in these fields than as described by the specification: 
> Unless otherwise noted, objects defined by this specification MUST NOT contain any additional members. 

However, also note this:
> Client and server implementations MUST ignore members not recognized by this specification.

Which means that if we add this "extension" to JSON API v1.0, it should not break any well-behaving JSON API v1.0 tools, because they are ordered to ignore our extra member.

### Alternative 2
If we want to *strictly* adhere to JSON API v1.0, the most sensible place to put this is in the top level meta field, since that is allowed to include whatever we want
> Where specified, a meta member can be used to include non-standard meta-information. The value of each meta member MUST be an object (a “meta object”). Any members MAY be specified within meta objects.

I.e., this would be ok:
```json
"meta": {
    "schema": "http://schemas.optimade.org/v1.0.0/structures.json"
}
```

@ltalirz, @giovannipizzi, @sauliusg, @blokhin: Any thoughts on the two alternatives above?
