### ISSUE TITLE
Representation of missing mandatory data

### ISSUE THREAD

**Issue by merkys** [Materials-Consortia/OPTIMADE#385]
In the COD there are [structures](https://www.crystallography.net/cod/1001012.html) lacking such OPTIMADE-mandatory attributes as cell parameters. Such entries serve more as bibliographic references, but nevertheless they might contain important data.

OPTIMADE requires (`MUST`) non-null cell parameters. Thus to stay compliant the COD must not expose such structures over OPTIMADE. I would like to know whether it is a general intention of OPTIMADE to exclude all structures that cannot fulfill `MUST` requirements of the specification, and whether all providers are happy with that. If not, then maybe we should think of a way to represent missing data, possibly by removing non-null constraints.

Pinging @sauliusg.

**Comment by ml-evs** [comment]
I'm not sure there is a problem here; you should be perfectly able to serve structures with missing `lattice_vectors` with the current specification (though maybe this is not what you mean by "cell parameters"?). 

The only "MUST" I can see wrt. `lattice_vectors` is that if the field is not null, then it MUST be a 3x3 array of floats/nulls. The overall field is also only a "SHOULD", only `structure_features` field is a "MUST".

Have I misunderstood the question?

**Comment by merkys** [comment]
You are absolutely right. I misread "SHOULD NOT be null". There is really no problem here, just my inattentiveness!
