### ISSUE TITLE
Database-provider-specific keys in all dictionaries

### ISSUE THREAD

**Issue by merkys** [Materials-Consortia/OPTIMADE#397]
As of v1.1.0, providers are allowed to add custom entry properties, provided they prefix them with provider-specific prefixes. I suggest extending this to allow custom keys in all dictionaries. Thus if a provider wants to add something to each of every species, for example, isotope, they will be able to do so, viz.:
```json
"species": [
  { "name": "13C", "chemical_symbols": [ "C" ], "_exmpl_isotope": 13 }
]
```
This would allow passing additional nonstandard information via the same OPTIMADE interface without dragging possibly huge parallel lists or tables. Viz. how isotope information would be carried conforming to v1.1.0:
```jsonc
"_exmpl_isotopes": { "13C": 13 } // here the key is the name of species
```

**Comment by rartino** [comment]
@merkys Do you agree that #401 closes this? (In #401 you seemed to say it only implements a subset of this issue?)

From the discussion in #401 I note that there presently does not seem to be a way to add output format-agnostic database-provider specific keys to a relationship. Do we want to have that feature? It is technically as easy to update the text that explains what a relationship is to add that any number of prodvider-specific keys and values associated with the relationship MAY also be included. And then, for the json output format explain where they should go (inside the meta field?).
