### ISSUE TITLE
Explicitly write in the specification text what is new and what changed in a given version with respect to previous versions

### ISSUE THREAD

**Issue by giovannipizzi** [Materials-Consortia/OPTIMADE#412]
While one could look into the release notes, a new person wanting to implement, e.g., a client for v1.2 of the specs might want to know what changed w.r.t. to 1.1 (so they can write a 1.1 compliant client as well) in an easy way, without going through the git history.

E.g. Python does have this, see e.g. [`os.environ`](https://docs.python.org/3/library/os.html#os.environ) that states

> Changed in version 3.9: Updated to support [PEP 584](https://www.python.org/dev/peps/pep-0584)’s merge (|) and update (|=) operators.

or [`os.fsencode`](https://docs.python.org/3/library/os.html#os.fsencode) that states

> New in version 3.2.
> 
> Changed in version 3.6: Support added to accept objects implementing the [os.PathLike](https://docs.python.org/3/library/os.html#os.PathLike) interface.

To simplify our life, we can decide to do this at release time (do a diff with the previous version, and add this `new`/`changed` flags). So we do all in one shot and we don't have to remember to do it for every PR.
This is why I'm marking this for v1.2.

However, in this case it would be good to add to the [wiki page describing how to make a new release](https://github.com/Materials-Consortia/OPTIMADE/wiki/New-release-%28How-to%29).

**Comment by merkys** [comment]
We already have a [CHANGELOG.md](../blob/develop/CHANGELOG.md).
