### ISSUE TITLE
Is "full" missing from list of `query_support` values?

### ISSUE THREAD

**Issue by JPBergsma** [Materials-Consortia/OPTIMADE#418]
In the examples on line 1164 and 1169 the field `query_support` has the value "full"
In the definition of query support (from line 1847 onward), "full" is however not listed as a valid value for the query support field.  I was therefore wondering if the option full is missing from the list of valid values for the query support field.

I also think that it should be "query-support" on line 1245 instead of "query"

**Comment by rartino** [comment]
It is "just" a typo in the example. "full" was replaced by "all mandatory" to be more clear on what full means.
