### ISSUE TITLE
Each DB provider should have a test sub-DB

### ISSUE THREAD

**Issue by giovannipizzi** [Materials-Consortia/OPTIMADE#44]
This would allow for
- centralized testing of the API (unit tests written only once and tested on all known/registered DB providers)
- easy checking  of the currently implemented features

Moreover, if we agree on the content of the test DB (say ~200 structures) each DB can store them in the internal format of the DB, and it is easy to check additionally that the way structures are returned by the API (e.g. in corner cases like partial occupancies, low-dimenasional systems, assemblies, ... - see #23) is consistent and correct across implementations.

**Comment by rartino** [comment]
I like this, but, specifically using the word SHOULD, i.e., an API implementation is still conformant without it.

**Comment by merkys** [comment]
At COD we already have a test API endpoint: http://www.crystallography.net/cod-test/optimade/info. Feel free to test it! Keep in mind that we also use that sub-database as a testbed, from time to time adding crafted crystal structures or removing them altogether.

**Comment by ml-evs** [comment]
Doing a bit of issue triage, I think this can be closed after the eventual approach we took with index meta-databases and the validation dashboard.
