### ISSUE TITLE
Replace property definitions x-optimade-property/property-uri with just an outer "$id" key?

### ISSUE THREAD

**Issue by rartino** [Materials-Consortia/OPTIMADE#442]
JSON schema apparently has a standard feature to indicate a URI for the schema, which is to have a key "$id". It seems to me this could replace our own identifier x-optimade-property/property-uri. Should it?

**Comment by ml-evs** [comment]
I'd be fine with this. What are we expecting this field to be set to for OPTIMADE properties? e.g., `https://github.com/Materials-Consortia/OPTIMADE/blob/v1.1/optimade.rst#chemical-formula-descriptive`?

With a bit of encouragement I could continue with #378 and get it hosted at `optimade.org` for a nice human-readable/linkable spec.

**Comment by JPBergsma** [comment]
I am closing this issue as PR #457 has been merged.
Or do you feel your question has not been answered sufficiently yet ? @ml-evs
