### ISSUE TITLE
Property definitions type for timestamp (and other non-json OPTIMADE types)

### ISSUE THREAD

**Issue by rartino** [Materials-Consortia/OPTIMADE#443]
I'm not sure how we missed this :-), but the definition of the `type` field in the property definitions go through each JSON data type and explain what it corresponds to in terms of OPTIMADE data types. But, that means it never says what to do for timestamps.

To keep the property format valid JSON schema, the standard type field needs to be "string". But, this means we need to add another type field (`x-optimade-type`?)  to spell out "datetime" somewhere.

This will also be important to figure out for other new datatypes we add in the future, e.g., there is a proposal for a SMILES datatype #436.

**Comment by rartino** [comment]
Right, but, an implementation that want to interpret the property definition in context of an output format that has a native timestamp datatype needs to be able to understand that a property definition of, e.g., `last_modified` refers to the OPTIMADE timestamp data type, and not to a string. 

I'm halfway convinced we should simply add a mandatory `x-optimade-type` that always spells out the OPTIMADE type name, but it adds redundancy for most data types. Maybe for now it is best to do as you say and rely on the "format" field. But, that means we need to invent our own format name for the upcoming SMILES datatype.

**Comment by ml-evs** [comment]
> I'm halfway convinced we should simply add a mandatory `x-optimade-type` that always spells out the OPTIMADE type name, but it adds redundancy for most data types. Maybe for now it is best to do as you say and rely on the "format" field. But, that means we need to invent our own format name for the upcoming SMILES datatype.

I'm with you now -- this seems like something we could easily add now if we want to, if it is just constrained to our existing types? (i.e., we don't want to support implementation-specific types)
