### ISSUE TITLE
Materials classes: periodic table elements groups

### ISSUE THREAD

**Issue by blokhin** [Materials-Consortia/OPTIMADE#448]
Dear colleagues,

we're now releasing the [periodic table](https://kit.metis.science/docs/components/periodictable) user interface component, and one of its features is the whole column or row selection, such as `chalcogens`, `actinides`, `period 6`, `group 11`, etc. While we are about to fully support such groups on MPDS (e.g. `{"classes": "tetrels, actinide"}` in our API `/v0` or `_mpds_classes HAS ALL "tetrels", "actinide"` in our API `/v1`) as well as in the other projects, I'm thinking if it makes sense to promote the names of these groups further to the standard.

Of course, their support should be absolutely voluntary, but I personally think it's way much easier to query just `alkaline` instead of `Be | Mg | Ca | Sr | Ba | Ra` or `period 2` instead of `Li | Be | B | C | N | O | F | Ne`. On top of that, it also stimulates reach and interesting queries exploring periodicity and chemical elements similarity. Note, this is relevant not only for the unary compounds, but for the compounds of any arity (binary, ternary), including those groups of elements.

Here is the [whole list of the element groups](https://github.com/basf/svelte-spectre/blob/a358d740317b21b7f709c4f790ebfc4cb3facd66/src/lib/components/PeriodicTable/chemical_content.json), as we are now supporting (or about to support) them.

What would be your opinion on that? Beware, there are some caveats on the singular-plural forms or case-sensitivity.

**Comment by JPBergsma** [comment]
For this to be really useful, all the servers should support it. 
This would however make it a bit more complicated to implement an OPTIMADE server, and I think we should try to keep this a simple as possible. So I am not sure that we should add this to the OPTIMADE specification.

I do think it would be a nice addition for a client, though.
Matthew has been working on creating an optimade client as part of the optimade-python-tools.
Perhaps it could be added there.

**Comment by merkys** [comment]
I support @JPBergsma opinion that this should be a client-side feature. Translation of class names to lists of elements in queries should not be difficult.

**Comment by blokhin** [comment]
@JPBergsma @merkys OK, I agree with you. We will support this feature in our [natural language parsing library](https://github.com/mpds-io/optimade-mpds-nlp) for clients.
