### ISSUE TITLE
Add support for $comment in property definitions

### ISSUE THREAD

**Issue by rartino** [Materials-Consortia/OPTIMADE#459]
JSON schema has in draft 7 added support to put comments in schemas via $comment: http://json-schema.org/understanding-json-schema/reference/generic.html#comments

When working on our property definitions in #445 I independently realized it would be useful to insert comments in the property definitions. So we should add this to the subset of JSON Schema that we allow.

**Comment by merkys** [comment]
What would be the target audience of comments? Maybe we can just put them to `description`?

**Comment by rartino** [comment]
It would be for comments that are relevant to property definition "developers" rather than "end users". Another difference is that you can put it on any level in a nested definition to comment e.g. the motivation behind setting a limit like "maximum" to something. I stumbled on the desire to insert a comment when I realized I wanted somewhere to explain why `common/element.yaml` doesn't have an `x-optimade-property` (it is because it isn't itself part of the OPTIMADE standard properties, it is just used as a target for '$ref' when we compose other standard properties.)

**Comment by merkys** [comment]
OK, this makes sense.

**Comment by ml-evs** [comment]
Closed by #457 (I think) or a related PR
