### ISSUE TITLE
Adding per property meta_data field.

### ISSUE THREAD

**Issue by JPBergsma** [Materials-Consortia/OPTIMADE#462]
In issue #410 the idea was raised to create a per property field for metadata.
There was still some discussion on how to name such a field. 
But for the moment, appending "_meta" to the end of the field name seems the most popular way to name this field.
I would like to use this metadata field for the ranged properties (See PR #452)
Before I can write a proposal for the metadata field: I however, still have a few questions/ ideas to discuss.

- Nested metadata fields ? Can a field in metadata have a metadata field of its own ?

- Do we want to return the metadata field when the main field is requested via response_fields ?

- Do we want to be able to “override” fields set in the property definition ? 
i.e. the value in the property definition would be the default for all entries, but individual entries can deviate from this.

**Comment by merkys** [comment]
@JPBergsma internal GitHub links in your post do not seem to work, could you please fix them? This way it would be easier to see the connected issues/PR, and possibly more people from related issues/PRs would find their way here.

To answer your questions:
> * Nested metadata fields ? Can a field in metadata have a metadata field of its own ?

Intuitively I would say no, but maybe there is a use case for this?

> * Do we want to return the metadata field when the main field is requested via response_fields ?

I would say yes.

> * Do we want to be able to “override” fields set in the property definition ?

I would say no. This might overcomplicate OPTIMADE.

**Comment by merkys** [comment]
> Would you consider an uncertainty margin/error bar for a value metadata ?

Good point. Currently OPTIMADE has no mechanism to communicate uncertainties and metadata could be a place to do so. Alternatively we may define properties with arbitrary suffices (for example, `_SU`), but I like metadata better.
