### ISSUE TITLE
Potentially mark 'Partial data' functionality as alpha/experimental

### ISSUE THREAD

**Issue by ml-evs** [Materials-Consortia/OPTIMADE#479]
In today's meeting we discussed "demoting" partial data to an experimental feature, to guard against the fact that no-one will be able to implement it before v1.2 is released.

The idea would be to add a note that gives us the freedom to make breaking changes to "partial data" in a future v1.x release.

**Comment by ml-evs** [comment]
Alternatively create 1.2-rc2 as a "everyone implement this" release candidate

**Comment by JPBergsma** [comment]
Isn't our development branch already a kind of experimental branch ? So that you know which features/changes are coming up.
So I think I prefer releasing a 1.3 soon after over having finished implementing the trajectory stuff, over putting it as an experimental feature in 1.2.

**Comment by ml-evs** [comment]
> Isn't our development branch already a kind of experimental branch ? So that you know which features/changes are coming up.
> So I think I prefer releasing a 1.3 soon after over having finished implementing the trajectory stuff, over putting it as an experimental feature in 1.2. 

Indeed, but this is exactly why partial data (already merged) should be marked as experimental so that we can still include any necessary changes arising from trajectories without holding up the 1.2 release.

**Comment by JPBergsma** [comment]
Couldn't we just leave out these changes from the next release branch ?
