### ISSUE TITLE
REST vs. GraphQL

### ISSUE THREAD

**Issue by blokhin** [Materials-Consortia/OPTIMADE#48]
Dear colleagues,

it seems [GraphQL](https://graphql.org) spec has many advantages over REST:

- better logical encapsulation and multiplexing
- more explicit implementation guidelines
- nice integration of query language with the schemata
- no overfetching

What do you think on including GraphQL into OPTiMaDe?

**Comment by blokhin** [comment]
![graphql](https://user-images.githubusercontent.com/177388/43270410-477fdd2c-90f5-11e8-939b-8bed85d9ac2c.png)

**Comment by rartino** [comment]
I think GraphQL may have been shortly mentioned during the first meeting. But, the idea was (and is) to stay as minimal as possible, and a home-rolled query language in REST may be less complex to work with. Nothing is preventing us at a future point to add GraphQL support onto the REST API, i.e., support both.

One thing that comes to mind is that we've designed our query language around the idea of a feature set that can be implemented as efficient queries regardless of backed database. How does that work with the GraphQL query language? It *looks* more no-sql oriented.

**Comment by blokhin** [comment]
An official documentation gives an answer:

>With GraphQL, you model your business domain as a graph by defining a schema; within your schema, you define different types of nodes and how they connect/relate to one another. On the client, this creates a pattern similar to Object-Oriented Programming: types that reference other types. On the server, since GraphQL only defines the interface, you have the freedom to use it with any backend (new or legacy!).

To summarize, GraphQL knows nothing about the data organization, it's just an abstracted type system allowing for complex hierarchical queries in a JSON dialect.

**Comment by blokhin** [comment]
To be closed in 2023 if GraphQL is no more mentioned in view of Optimade.

**Comment by blokhin** [comment]
Closing. FYI some relevant (negative) experience https://bessey.dev/blog/2024/05/24/why-im-over-graphql

**Comment by merkys** [comment]
Thanks for an interesting link @blokhin. I was not aware of GraphQL drawbacks before.
