### ISSUE TITLE
Specification not rendering on GitHub

### ISSUE THREAD

**Issue by ml-evs** [Materials-Consortia/OPTIMADE#492]
For some reason the spec can no longer be previewed on GitHub. I'm not sure if this an ephemeral problem, a GitHub bug or something wrong with our files (see https://github.com/orgs/community/discussions/86715).

**Comment by ml-evs** [comment]
> Old versions like https://github.com/Materials-Consortia/OPTIMADE/blob/6f1e115094ec256c262df712a35c86f4d3e6d1c7/optimade.rst fail to render when they definitely used to (Firefox Developer Edition, no extensions)

_Originally posted by @ml-evs in https://github.com/Materials-Consortia/OPTIMADE/issues/493#issuecomment-1889488011_

**Comment by rartino** [comment]
Clearly something changed on GitHub's side; even going back to the original rst file right after we converted the specification doesn't render.

**Comment by ml-evs** [comment]
Feel free to pretend to be another effected project in my linked discussion :P I think this must have changed in the last hour or so...

**Comment by rartino** [comment]
I think a fairly high level of complexity is needed to trigger this; here is a somewhat long rst file that still renders correctly: https://github.com/httk/rsttools/blob/main/docs/rstslide/presentation.rst

**Comment by ml-evs** [comment]
I'll remove our custom roles and try to commit again to #493, see if it makes a difference

**Comment by ml-evs** [comment]
After some fixes on GitHub's end, we are now *mostly* back to where we were. The only thing that no longer renders is the table of contents (and hopefully they are working on this). Given that we have HTML builds now anyway (tracked by #501), I will close this issue.
