### ISSUE TITLE
Clarify default licensing value

### ISSUE THREAD

**Issue by ml-evs** [Materials-Consortia/OPTIMADE#494]
https://github.com/Materials-Consortia/OPTIMADE/blob/b3fd0be75ee531a464d4956a781271170fd6a8f0/optimade.rst#L1263

`available_licenses` is an optional field, we should highlight what the missing value implies (e.g., database should be treated as unlicensed unless specifically listed elsewhere out-of-band).

**Comment by merkys** [comment]
Would it suffice to say that the missing value for `available_licenses` means the same as an empty list, as explained in the line you cite?

**Comment by ml-evs** [comment]
I'm not sure, as the field is optional it is explicitly allowed to be `null` (or missing altogether) which is undefined I think. I don't know if that should treated differently to `[]` but we should at least add a note that `null`/missing means all bets are off.

**Comment by merkys** [comment]
How about this:
> Unknown value or an empty list indicates that none of the SPDX licenses apply for the entirety of the database and that the licensing situation is clarified in human readable form in the field :field:`license`.

From section "Properties with an unknown value" of the specification I think it should be clear that unknown value is the same as `null`.

**Comment by rartino** [comment]
Maybe we should move this over to a PR so we can do explicit edit suggestions but regarding this:

> Unknown value or an empty list indicates that none of the SPDX licenses apply for the entirety of the database and that the licensing situation is clarified in human readable form in the field :field:license.

IMO strictly speaking a missing value should mean the database makes no commitment to the data being covered by such a license (and hence the client cannot assume it). But, it should not be a violation of the standard to omit the field even if the content happens to be covered by an SPDX license.

I'll take the opportunity to squeeze in here the issue I talked about on the last web meet: it would be great if we can amend these fields according to this:

- `available_licenses` apply to the whole database, including all individual entries, all metadata, **and the content and structure of the database itself** in case any legal protection applies to it, see e.g., https://europa.eu/youreurope/business/running-business/intellectual-property/database-protection/index_en.htm and https://intellectual-property-helpdesk.ec.europa.eu/regional-helpdesks/european-ip-helpdesk/europe-frequently-asked-questions_en#Database_Protection_Domain_Protection

- a new field `available_licenses_for_entries` that declares licenses available for individual entries and their metadata and data extracts that do not constitute "substantial parts of the database" in the sense this term is used in legal documents that describe database copyright, in case any protection applies to such individual entries.

With the note that a client can assume any license included in the first field also applies for any use covered by the second field, but not the other way around.
