### ISSUE TITLE
Require conversation resolution before merging

### ISSUE THREAD

**Issue by vaitkus** [Materials-Consortia/OPTIMADE#495]
During the PR review process conversations often become outdated as thus much less visible. I propose that we enable the "Require conversation resolution before merging" option [1] on the `develop` (and possibly other) branches to ensure that all comments are properly addressed.

[1] https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#require-conversation-resolution-before-merging

**Comment by ml-evs** [comment]
Agreed, they can be hard to find. I've just enabled it, please raise any disagreements here otherwise we can close this soon.

**Comment by ml-evs** [comment]
I think there was no disagreement about this when raised at a recent discussion, so I'll close this now.
