### ISSUE TITLE
Allowing for unknown/null coordinates

### ISSUE THREAD

**Issue by giovannipizzi** [Materials-Consortia/OPTiMaDe#50]
As discussed in #49, we split part of the discussion of #23 to this new issue.

From the comment of @rartino in #23:

> There are differing opinions on how to handle systems with atoms at unknown coordinates. How to resolve this is deferred into a separate issue. Two alternatives is to allow null in the coordinate lists, OR put an extra optional property that alongside the known coordinates describe the information that exists about the atoms at unknown positions.
> - The separate x,y,z coordinates are allowed to be given as 'null' if unknown. E.g., for disordered systems where coordinates are not fixed, and certain situations where light atoms can be near heavier atoms without knowing exactly where. However, we note that the latter situation can alternatively be represented by a species ~ "CH4", which can also be used in an assembly with "C" to indicate that it is not clear which one of the C atoms has the four H. (If it is known that all 4 always sits on on C...)
> - There is an extra required property `all_coordinates_known` that is true or false depending on whether any coordinate is a null value. (So clients can easily use filter to get only structures where all coordinates are known.)

And from @sauliusg :
> Actually, there seems to be the third way to represent atoms with unknown positions: specify no site for them (so no 'null' coordinates), and have a species that is on *no* site.

**Comment by giovannipizzi** [comment]
Some snippets of text originally proposed in #49, that will now be removed from that PR, and that can be reused here if this is approved.

In `cartesian\_site\_positions`
>   * If a component of the position is unknown, the `null` value should be provided instead. Otherwise, it should be a float value, expressed in angstrom. (See also the property `all_coordinates_known`).

> ### <a name="h.6.2.8">6.2.8. all\_coordinates\_known</a>
> * Description: A boolean indicating if all coordinates are known and specified in the `cartesian_site_positions` list.
> * Requirements: 
>   * This property is required.
>   * If at least one component of the `cartesian_site_positions` list of lists has value `null`, then the `all_coordinates_known` property must be set to `false`, otherwise it must be set to `true`.

**Comment by rartino** [comment]
I'm going to append here some thoughts on this that I wrote down from discussions with others right after the CECAM meeting.

Two things had me (and I think a few others) hesitate in simply allowing 'null coordinates' in the `cartesian_site_positions` list:
 - Many alternative data formats won't be able to efficiently handle a float matrix where some entries can be null. For example, hdf5, or float arrays in numpy (it works with object arrays, though.) In general we have so far tried to stick with one datatype per datum. A float that can also be a null breaks this to some extent.
 - There are more scenarios of ways for structural information to be "unknown" than what is covered by allowing some coordinates to be null. For example, one may not know exactly how many atoms of some kind are missing (e.g., hydrogens). It may be good to have a complete picture of what OPTIMaDe should be able to represent in terms of unknowns before implementing some partial, insufficient, solution.

Hence, it is my present position that it would be better to try to mimic what was done with the 'assembly' property in the OPTIMaDe structure definition; i.e., to break out all forms of data having to do with 'unknowns' in relation to structural information in another property alongside `cartesian_site_positions`.

With an 'assembly'-like property there may be the concern that some implementations may be so oriented towards the simplest structure definition that they forget to check if, e.g., a `missing_structural_info` property exist. This point is to some degree already relevant for the 'assemblies' property. Hence, we should perhaps in a separate issue decide on a way to make it very clear which of these "optional features" are used in a structure, so it is very straightforward for a client to limit output to structures that uses features it is prepared to handle.

**Comment by giovannipizzi** [comment]
Maybe we should try to list all cases we want to cover where there are unknown coordinates? 
The only two cases that come to my mind (but most probably they would be anyway cases in which we would discard structures for simulations) are unknown positions (and often I imagine these would be all three positions of a given atom, rather that just one coordinate, that I don't see as a common case).
If this is the only case (but if you have more, please comment) then we can just have a list of species with unknown coordinates, like `formula: "CH4"`, with only one site specified (C, with its coordinates as usual) and a list `'unkwown_species': ["H", "H", "H", "H"]`.

Anyway, even if we decide to go for the option of specifying single uknwown coordinates, with the extension of #51 it might still be ok to allow for null coordinates: clients might completely ignore the structure, and those who understand it will anyway have their internal way of dealing with it - e.g. putting a random value there, storing coords as an array of floats, and then also creating a mask of "True/False" known coordinates as an array of bools. I think this is better than having the Optimade server put random numbers there and then giving the mask in a way similar to "assemblies", because there is a higher risk of clients ignoring the list of features and thinking those random numbers are actually coordinates.

I wouldn't worry too much about how to optimise storage (if we want to store null coordinates) because anyway the client will have to serialize/deserialize the data, and it can decide the optimal way of storing it after parsing the REST response.

**Comment by rartino** [comment]
> I wouldn't worry too much about how to optimise storage (if we want to store null coordinates) because anyway the client will have to serialize/deserialize the data, and it can decide the optimal way of storing it after parsing the REST response.

The spec already opens for optimade replies to be returned in other formats than json. To implement a database-specific binary `_exml_hdf5` response format (that later may eventually be adopted as an official optional alternative to json) is something that isn't far off for me, and it would be nice to be able to keep that data format close to the json one. This would be greatly helped by not mixing datatypes in the fields. I think that policy is also generally a very good idea to simplify implementations.

> Maybe we should try to list all cases we want to cover where there are unknown coordinates?

It would be good to at least have feature parity with cif, so that all existing cif structures can be represented. Other than that, I don't feel strongly about the format and what should be/shouldn't be included. So, I really would appreciate input for what cases must be supported from people who are more knowledgeable with this aspect in cif, @sauliusg, @merkys.

(But clearly there are many technical possibilities: unknown coordinates restricted to a subspace; atoms in unknown positions 'close to' other atoms, e.g., hydrogens in some molecules; an unknown species at a known position; unknown count of some species, which is common with e.g., hydrogens, etc.)

**Comment by giovannipizzi** [comment]
Suggestion: use `NaN` since it's a valid float value (e.g. supported by HDF5).
However in JSON `NaN` is not allowed (in strict mode). However we could replace `NaN` with `null` in JSON and this might be the solution to the problem.

**Comment by giovannipizzi** [comment]
Note: it's important to address #17 as well if we implement this

**Comment by sauliusg** [comment]
Could we handle the missing coordinates, i.e. coordinates having `null` values, in the same way that we handle `null` values in other fields as per PR #17?

**Comment by sauliusg** [comment]
I support giovannipizzi and suggest using `null` in JSON to represent floating values that are not know. For properties that have type `float` they can be converted to NaN by underlying representation, if necessary.
