### ISSUE TITLE
Final sweep of formatting fixes

### ISSUE THREAD

**Issue by ml-evs** [Materials-Consortia/OPTIMADE#510]
I would consider that we are now in an approximate "feature freeze" for v1.2.

As GitHub has blessed us with being able to render our specification again, we probably need another wave of formatting fixes, that we need to ensure work both in the RST version and in the HTML builds. For example, I now see several indented lists that are being rendered as quotes by GitHub.

**Comment by merkys** [comment]
What about `\_`'s? Do we have to escape all `_`'s for RST or now? Currently we have a mix of `_`'s and `\_`'s.

**Comment by rartino** [comment]
Looking for it, I see a lot of `\_` inside text-role-marked text, which renders with the backslash. At least all those backslashes should be removed. All other `_` characters should probably be escaped to avoid ambiguity with link-type markup.
