### ISSUE TITLE
OPTiMaDe logo

### ISSUE THREAD

**Issue by blokhin** [Materials-Consortia/OPTIMADE#67]
Please, see https://github.com/Materials-Consortia/materials-consortia.github.io/issues/1

PS sorry for cross-posting!

**Comment by blokhin** [comment]
![optimade_logo_draft_110619](https://user-images.githubusercontent.com/177388/59261249-6b252180-8c3d-11e9-9680-c5857fa1e898.png)

(Draft, to be polished.)

**Comment by gmrigna** [comment]
[logo.pdf](https://github.com/Materials-Consortia/OPTiMaDe/files/3276355/logo.pdf)

**Comment by giovannipizzi** [comment]
Here is my proposal.

Small version: <img width="100" alt="small" src="https://user-images.githubusercontent.com/16132028/59370833-b295d580-8d43-11e9-8dff-e62a66ba7f2d.png">

Large version: <img width="345" alt="large" src="https://user-images.githubusercontent.com/16132028/59370836-b45f9900-8d43-11e9-8e55-30e8282f7884.png">

Explanation: Outside there are the various databases (various colors), possibly more of them for every provider and connected among them, but only partially.
Inside there is the full network (same color) generated by Optimade that connect all entries.

**Comment by blokhin** [comment]
Below are some variations of Giovanni's logo, which I actually find very pointful.

**Comment by blokhin** [comment]
![o1](https://user-images.githubusercontent.com/177388/59644015-6267aa80-916b-11e9-9547-8cc38c324595.png)

**Comment by blokhin** [comment]
![o2](https://user-images.githubusercontent.com/177388/59644024-6bf11280-916b-11e9-93d3-9fae013c87db.png)

**Comment by blokhin** [comment]
![o3](https://user-images.githubusercontent.com/177388/59644030-71e6f380-916b-11e9-936d-ad03398f831d.png)

**Comment by ltalirz** [comment]
I like @giovannipizzi 's draft for the logo, including the font chosen.

As suggested by @blokhin , we should choose the OPTiMaDe capitalization (unless we decide to drop this capitalization entirely)

**Comment by giovannipizzi** [comment]
Yes, I agree we should agree on the capitalisation - personally, I think the current one `OPTiMaDe` is a bit cumbersome to remember and write, see also e.g. [this commit where we had to fix it in a few places](https://github.com/Materials-Consortia/OPTiMaDe/pull/115/commits/e2d0a2d4455a2cb1a936d66113a131210fde7508) (and also it does not really much the tagline "Open Databases Integration for Materials Design"...) and I would favour simplifying it to one of the following three variants - and uniform this everywhere:

1. `Optimade`
1. `optimade`
1. `OPTIMADE`

I would probably go for 3, but I'm happy to listen to other opinions

**Comment by merkys** [comment]
> personally, I think the current one `OPTiMaDe` is a bit cumbersome to remember and write

I'm already quite used to it to the point of having no problems in typing it correctly :) So my personal opinion would be to stick to it as it is.

**Comment by rartino** [comment]
Great work with the logos! I particularly like @giovannipizzi's version, and I do like that font. Regarding the capitalization, would it be ok to ask for a version of the large one with the OPTiMaDe capitalization so we can compare? (I suspect that you are right that all caps look better, but it is difficult to know for sure without having seen it rendered in the same font.)

**Comment by blokhin** [comment]
![logo](https://user-images.githubusercontent.com/177388/59956762-8fc99680-9492-11e9-9461-c1b39b7f267d.png)
PS here's the archive with the font and the editable source in vectors for Inkscape, please, feel free to play: 
[optimade_logo.zip](https://github.com/Materials-Consortia/OPTiMaDe/files/3316343/optimade_logo.zip)

**Comment by ltalirz** [comment]
@rartino I think the point Giovanni is trying to make is not that `OPTiMaDe` does not look good (I think it looks perfectly fine - one could argue that it looks even a bit more interesting than `OPTIMADE`). In practice, however, it requires every outsider who wants to mention it (in a paper, press release, ...) to look up the spelling.
I just know from experience that the "Quantum ESPRESSO" people already have a hard time getting people to use the right capitalization while theirs is arguably quite a bit easier to remember.

I would personally vote for `OPTIMADE`.

@gmrigna Can I ask what the original reasoning for the particular choice of capitalization was?

**Comment by gmrigna** [comment]
The original reasoning starts from "Open Databases Integration for Materials Design" using "Op" from "Open", "t" from "Databases", "I" from "Integration", "Ma" from "Materials", and "De" from "Design". Then, consonants are all capitalized and vowels all small letters (except from the first letter "O"): hence, OPTiMaDe.
I personally do not have a strong opinion about this. I perfectly get the point of @giovannipizzi

**Comment by gmrigna** [comment]
Based on Giovanni's logo, I have one more suggestion.
[optimade_logo.pdf](https://github.com/Materials-Consortia/OPTiMaDe/files/3318368/optimade_logo.pdf)

**Comment by giovannipizzi** [comment]
I like @gmrigna's logo, probably even more than mine!
A few more comments/notes:
- one difference between @blokhin and my logo is that the "legs" out of the hexagon are parallel to sides in @blokhin's version, rotated by 30degrees in mine. I don't know what is better (but maybe I prefer @gmrigna's version in the end)
- For what concerns @gmrigna's logo, I would probably just increase the ratio of thickness between the central circle and the outer arcs (probably increasing the thickness of the circles, and maybe also increasing also the size of the points on the circle - this will also improve a bit, possibly, the rendering of the logo at very small sizes
- Also, for the font, I still prefer the one I had chosen. This is the font "Raleway" that [can be downloaded from Google Fonts](https://fonts.google.com/specimen/Raleway).
- I attach here as requested a version with the "standard" capitalisation:
  <img width="659" alt="img" src="https://user-images.githubusercontent.com/16132028/59997812-37df8b00-965e-11e9-9453-cfbc0e919c16.png">
- I also attach the SVG version (even if I didn't spend too much time aligning circles - if this logo is chosen, I would redo it with proper alignment). Note also that you need to install the font mentioned above first (note also that due to limitations in file extensions, you need to download and remove `.txt`): [optimade2.svg.txt](https://github.com/Materials-Consortia/OPTiMaDe/files/3319575/optimade2.svg.txt)

**Comment by gmrigna** [comment]
I am not sure that I perfectly got what @giovannipizzi meant with the circle sizes. So, here is the svg file (which actually use the "Raleway" font) [optimade_logo.svg.txt](https://github.com/Materials-Consortia/OPTiMaDe/files/3320502/optimade_logo.svg.txt)

**Comment by rartino** [comment]
I like @gmrigna's latest one (but maybe without a color gradient.) However, the overall shape did lead my mind a bit to the [biohazard symbol](https://en.wikipedia.org/wiki/Biological_hazard); if others see the same thing, then perhaps it is something to be careful with. I'll try an alternative that takes the design away from that. Here is what I arrived at:

![optimade_logo_ra3](https://user-images.githubusercontent.com/2890905/60020175-c0c2ea80-968f-11e9-902a-31f5dbceea43.png)

[optimade_logo_ra3.svg.txt](https://github.com/Materials-Consortia/OPTiMaDe/files/3320862/optimade_logo_ra3.svg.txt)

**Comment by merkys** [comment]
> However, the overall shape did lead my mind a bit to the [biohazard symbol](https://en.wikipedia.org/wiki/Biological_hazard)

I see it too. I'm happy with @rartino's suggestion, but could you just adjust all the "connections" to make them regularly spaced (120 degrees)?

**Comment by gmrigna** [comment]
The original red hexagon of @giovannipizzi was meant to represent the OPTiMaDe API, while the purple, green, and blue branches symbolized the APIs of the different projects. The whole idea was that OPTiMaDe is creating a connection. I had simply rounded everything and added a few more projects (using other colors and adopting the gradient to show the unity, note that this could be change into a unique color). All this has completely disappeared in @rartino proposal. I do not perceive what the colors are and where OPTiMaDe is. @rartino some explanation maybe?

**Comment by blokhin** [comment]
It reminds me the Olympic games

**Comment by rartino** [comment]
I don't see them as so different, but perhaps visually it connects more to @blokhin's original proposal. 

It shows providers (colors + hollow circles) that provide databases (solid circles) interconnected and communicating via a common protocol, OPTiMaDe. Some of the databases organize as parts of a shared OPTiMaDe network which forms the "three leaf lily shape" of interconnectedness in the center. Some other databases (the other solid circles) are provider subdatabases which are one step removed from that network. The overall shape is meant to illustrate the providers interconnected in a three-way "handshake" as a very abstract version of @blokhin's design but with three participants.

@blokhin I see what you are saying about olympic rings. That may not be a good thing for this design. 

Is the plan still to hand off these as a starting point to someone with real design experience?

**Comment by blokhin** [comment]
Yes. But may be let's vote for all the options posted here, so that we could at least determine the favorite(s)? Let me select an appropriate voting mechanism, ideally, integrated into GitHub...

**Comment by rartino** [comment]
How about the number of :heart: emoticons on each post with a concrete suggestion. (I opt for :heart: because so far none have been placed on any posts here yet, and we don't want to count an old thumbs up as a vote from someone who left the discussion.)

**Comment by dwinston** [comment]
I ❤️ ed @blokhin's Jun 11 draft because I love the cartooniness and the clear anthropomorphic cooperation. But I also ❤️ ed @giovannipizzi's latest, which I like because I see the outermost nodes as non-OPTiMaDe dbs that nevertheless benefit from OPTiMaDe by connecting to OPTiMaDe-interfacing dbs.

**Comment by gmrigna** [comment]
It seems that @giovannipizzi proposal (https://github.com/Materials-Consortia/OPTiMaDe/issues/67#issuecomment-504884406) is clearly leading.
@blokhin Is it still your intention to send it to a designer? Or shall we simply try to fine tune it ourselves?

**Comment by blokhin** [comment]
Great, we now have the preferred candidate! I will send it to a designer for polishing. As expected, there will be several modifications, so we'll probably vote again (in a separate thread).

**Comment by blokhin** [comment]
Please, see https://github.com/Materials-Consortia/OPTiMaDe/issues/185
