### ISSUE TITLE
Extending "reserved keywords"

### ISSUE THREAD

**Issue by CasperWA** [Materials-Consortia/OPTiMaDe#70]
There may be a need/want to add reserved words. Now, only `info` is a reserved keyword.

> Technically, I think only `info` needs to be reserved in the sense described under `ID`, since the point is to not get collisions between, e.g., /structures/info and /structures/42. If we intend to actually reserve our other endpoint names here, then `extensions` should also be in this list. (In fact, it might be a very good idea to at least also reserve `extensions`, since it facilitates future use cases where someone needs to add endpoint-specific extensions...)

_Originally posted by @rartino in https://github.com/Materials-Consortia/OPTiMaDe/pull/68_

**Comment by CasperWA** [comment]
Another related review comment:

> [...] If we are serious with this, it should say here that IDs cannot collide with any of the reserved words. I'm a little scared of this though; how are people going to be sure we don't add future reserved words that collide with their current IDs?

_Originally posted by @rartino in #68_

**Comment by merkys** [comment]
We could in principle "invert" the URLs a bit, i.e.,

* `/structures/info` -> `/info/structures`
* `/structures/extensions/42` -> `/extensions/structures/42`

This would effectively clean up the `/<endpoint>/` namespace. What you think?

**Comment by CasperWA** [comment]
> We could in principle "invert" the URLs a bit, i.e.,

I think this makes complete sense for `info`, while it doesn't seem to make sense for `extensions`, since I think of it as being on par with `structures`, i.e., an provider-specific endpoint.

**Comment by rartino** [comment]
But, we don't allow /structures/extensions (right?), so isn't that endpoint already "inverted" in @merkys sense?

I actually like @merkys suggestion a lot. It essentially means all limits on the id can be removed.

If we then also say that ID is URL-encoded / URL-decoded when used in `/structures/<id>` it seems to me we can ditch one of our three ID definitions. (Presumably `local_id`).

**Comment by merkys** [comment]
> But, we don't allow /structures/extensions (right?), so isn't that endpoint already "inverted" in @merkys sense?

I suggest using `/extensions/structures/` instead of `/structures/extensions/`. Therefore namespace for `<id>` in `/structures/<id>` becomes completely clean.

> If we then also say that ID is URL-encoded / URL-decoded when used in `/structures/<id>` it seems to me we can ditch one of our three ID definitions. (Presumably `local_id`).

Good point with URL-encoding. I'd happily throw away the `local_id`.
