### ISSUE TITLE
Consider rewriting/updating the HTTP Response Status Codes

### ISSUE THREAD

**Issue by CasperWA** [Materials-Consortia/OPTiMaDe#71]
Lifted from PR #68.

> (...) I also don't like those comments in this table anyway. People may think those are supposed to be included as part of the response message, and that really shouldn't be the case. (These messages are not meant to vary with code other than localization). Should we remove them and instead focus on being more clear in the specification on for what conditions which errors are supposed to be returned? Furthermore, I also think this table misses some error codes specified by the jsonapi specification...

_Originally posted by @rartino in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MjM2NjMzNDQw/pull_request_reviews/more_threads_

**Comment by ltalirz** [comment]
@fawzi says : JSON API specifies, we should be using thise
