### ISSUE TITLE
JSON API headers for Index Meta-Database

### ISSUE THREAD

**Issue by CasperWA** [Materials-Consortia/OPTIMADE#72]
Lifted from PR #68.

> (..) I think in the final version of the pull request that put this info here, we lost a sentence either here or elsewhere saying that these endpoints on index meta-databases are exempt from the jsonapi header requirements on the `Content-type` and `Accept` headers, and may serve the response with any `Content-type`.
> 
> But maybe this is something we should take in a separate PR, since it isn't only a cosmetic change. It seems very important, though.

_Originally posted by @rartino in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MjM2NjMzNDQw/pull_request_reviews/more_threads_

**Comment by rartino** [comment]
@sauliusg, @giovannipizzi  This is the issue we discussed in the teleconference. @sauliusg said he would post a new issue where we could discuss it. But that isn't actually necessary; we can have the discussion here.

**Comment by rartino** [comment]
Note: there is now a concrete PR to resolve this issue, perhaps we should continue the discussion there: #236
