### ISSUE TITLE
Uniqueness of ids

### ISSUE THREAD

**Issue by merkys** [Materials-Consortia/OPTiMaDe#73]
We have to decide whether `id`s are unique in:
1. a namespace (structure with `id` of 1 and calculation with `id` of 1 coexist) or
2. a database (no two entries with the same `id` can coexist in a database, just like issues and PRs on GitHub).

I personally prefer option 1. For example, JSON API uses tuple of `type` and `id` to uniquely identify an entry in the database.

**Comment by merkys** [comment]
Issue was brought up in a discussion of #21.

**Comment by dwinston** [comment]
@merkys I believe [https://jsonapi.org/format/#document-resource-objects](https://jsonapi.org/format/#document-resource-objects) gives some guidance:

> Within a given API, each resource object’s type and id pair MUST identify a single, unique resource. (The set of URIs controlled by a server, or multiple servers acting as one, constitute an API.)

Thus (type, id) is unique in the database, but an id may appear in multiple entry types.

**Comment by merkys** [comment]
Citing [4.1.2. JSON API Response Schema](https://github.com/Materials-Consortia/OPTiMaDe/blob/develop/optimade.md#412-json-api-response-schema):

> **id**: a string which together with the type uniquely identifies the object, this can be the local database ID

Thus I consider this issue resolved. However, it would be beneficial to describe this property in the term definition and refer to the term definition elsewhere in the text.

**Comment by CasperWA** [comment]
Closed in PR #104.
