### ISSUE TITLE
Where is our "working" spec for server/client development?

### ISSUE THREAD

**Issue by dwinston** [Materials-Consortia/OPTiMaDe#76]
We need a document where we can determine if a repository issue can be "closed" or not, and which people can reference this week for server/client development.

[https://github.com/Materials-Consortia/OPTiMaDe/blob/develop/optimade.md](https://github.com/Materials-Consortia/OPTiMaDe/blob/develop/optimade.md)? Currently labeled "v0.9.8-develop".

Or
[http://www.optimade.org/optimade](http://www.optimade.org/optimade) / [https://github.com/Materials-Consortia/OPTiMaDe/blob/master/optimade.md](https://github.com/Materials-Consortia/OPTiMaDe/blob/master/optimade.md)? Currently labeled "v0.9.5".

**Comment by CasperWA** [comment]
I believe issues can be closed if they are implemented in the develop spec.

There are rather significant changes from the two versions, it would be beneficial for server/client developers to defer to the develop version as a rule of thumb, I think. Whether a new branch is needed for editing or adding to the specs for server/client developers I don't know.
I think the best approach would be to create an issue with the change that is intended and then a PR based on that issue, trying to merge it into the develop version, keeping up with semantic versioning.

I may have misunderstood your intention with this issue, so please feel free to clarify if I completely missed the point :)

**Comment by dwinston** [comment]
My issue is that I have been developing against [http://www.optimade.org/optimade](http://www.optimade.org/optimade) For this issue to close, I would at least like a warning at the top of http://www.optimade.org/optimade that redirects developers to https://github.com/Materials-Consortia/OPTiMaDe/blob/develop/optimade.md as the latest working version of the spec. Does this make sense?

**Comment by CasperWA** [comment]
> (...) Does this make sense?

Sure! :) This should be added to the `master` branch README, with a link and an explanation.

**Comment by rartino** [comment]
Closed by #79 (right?)
