### ISSUE TITLE
Introduce "warning" messages under meta

### ISSUE THREAD

**Issue by CasperWA** [Materials-Consortia/OPTiMaDe#80]
Related to the discussion in PR #66 between @merkys and @CasperWA.

### Suggestions

- Top-level `errors` should be for _critical_ errors only. In accordance with JSON API, if an error occurs, ONLY the top-level `errors` should be returned with a [JSON Error Object](https://jsonapi.org/format/#error-objects) and the appropriate HTTP error code.
- The keyword `warnings` should be reserved under the top-level `meta`, to include errors or rather warning messages that are _non-critical_.

### Possible use cases

An example of a use case may be that a query keyword was misspelt from the client side (something that the client developer would definitely want to know and correct). This will according to the current spec result in the keyword to be ignored, and an otherwise normal response.
A solution to this would be for a warning message and that the client always checks for the presence of the `warnings` key under `meta` and relay these messages in a development environment (or even in production if needed).

Another example is for deprecation warnings to be expressed under this keyword.

**Comment by giovannipizzi** [comment]
I also agree this is important.
My suggestion:
- I would require that `warnings` is a list of warnings (and we need to define what a warning looks like - probably the same as errors?); 
- if no warning is there, the server MUST still provide the key with an empty list (so that also a naive client implementer that does not read the specs will see that there a field exists for listing warnings

**Comment by CasperWA** [comment]
> * I would require that `warnings` is a list of warnings (and we need to define what a warning looks like - probably the same as errors?);

Yes. This is what we have now suggested in the PR #85.

> * if no warning is there, the server MUST still provide the key with an empty list (so that also a naive client implementer that does not read the specs will see that there a field exists for listing warnings

I can gel with this. However, it is not in the "spirit" of the JSON API, where the `"errors"` field is _only_ present, if an error occurs. But since `"warnings"` are not standard JSON API stuff, then it makes sense to help a naive client in this way.
