### ISSUE TITLE
versioning guideline

### ISSUE THREAD

**Issue by ltalirz** [Materials-Consortia/OPTiMaDe#88]
I've added brief instructions on how to do versioning going forward on the wiki:
https://github.com/Materials-Consortia/OPTiMaDe/wiki/Versioning

Let me know if these sound reasonable. I'll close this issue once I've had some sort of feedback from the people assigned.

**Comment by CasperWA** [comment]
Looks good @ltalirz.

However, according to the short discussion, I think you should add explicitly that the version will only _ever_ be upped in the master branch, never in the develop branch.
This also means that it may not always be enough to simply "remove the `-develop` suffix" as is written on the wiki. One may have to change to 0.10.0 or 1.0.0, and not keep 0.9.9 (which will be the new develop version, when the master spec version is upped).

**Comment by CasperWA** [comment]
Furthermore, maybe "`v0.9.6 and v0.9.7 were never tagged" is not relevant, but rather that they were never released (as stable versions).

**Comment by ltalirz** [comment]
Hi @CasperWA 

> However, according to the short discussion, I think you should add explicitly that the version will only ever be upped in the master branch, never in the develop branch.

That is not quite what I had in mind (and it is not what e.g. the git flow model would suggest).
I've updated the wiki to more clearly reflect the workflow I have in mind:
https://github.com/Materials-Consortia/OPTiMaDe/wiki/Versioning

> Furthermore, maybe "v0.9.6 and v0.9.7 were never tagged" is not relevant, but rather that they were never released (as stable versions).

tagging and releasing is kind of equivalent on github, since github shows all tags under "releases".
Still, I agree this is github-specific and will adapt the text accordingly.

**Comment by sauliusg** [comment]
Looks OK for me.

>  develop: Remove the -develop suffix from the version number in the optimade.md specification
> master: Merge the develop branch into the master branch

Just a thought: maybe we change the order of these actions: first merge into `master`, and then remove the `-develop` suffix _in the master_. In this way the code in the `develop` branch will never be without the `-develop` suffix.

**Comment by ltalirz** [comment]
@sauliusg Good point, I've made the change.

**Comment by ltalirz** [comment]
Closing this following feedback.
