### ISSUE TITLE
Diagnostics of misspelled property names in Filter queries

### ISSUE THREAD

**Issue by sauliusg** [Materials-Consortia/OPTiMaDe#92]
If property name is not recognised by the queried end-point, an error diagnosis would be appropriate. However, we also want to formulate the following queries:

`filter=_aida_bandgap<2.0 OR _mp_bandgap<2.5`

and then send the same query to AiiDA-supported and MP OPTiMaDe endpoints.

For these queries to succeed, the following behaviour is suggested:

- if a database receives a query filter with universal Optimade properties (i.e. defined without a database prefix, and deemed universal for all databases), or a property with database private prefix (e.g. _cod_ for the COD database), then the database MUST check if the provided property names are known, and MUST return an appropriate error code if they are not known the database.

- if a database received a query filter with a property from an **unknown** database, the end-point MUST behave as if that property is unknown, i.e. is if it has the value `null`. If the database prefix of the unknown property is similar to that of a known database, the response MAY issue a corresponding warning.

**Comment by merkys** [comment]
Therefore:

* unrecognized universal property results in an error (HTTP 400 or the like);
* unhandled database-specific property results in a warning.

Sounds good to me.

**Comment by merkys** [comment]
Fixed by #162
